### ISSUE TITLE
udacimak render issue

### ISSUE THREAD

**Issue by MdTalhaZubayer** [udacimak/udacimak#100]
× Getting Youtube video id 9QadFJRKrEA information
2020-03-31T07:17:17.124Z [error]: ERROR: Command failed with exit code 3221225781: C:\Users\mdt51\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin\youtube-dl.exe --dump-json -f best -f=22/18/17 --encoding utf8 http://www.youtube.com/watch?v=9QadFJRKrEA
STACK: Error: Command failed with exit code 3221225781: C:\Users\mdt51\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin\youtube-dl.exe --dump-json -f best -f=22/18/17 --encoding utf8 http://www.youtube.com/watch?v=9QadFJRKrEA
    at makeError (C:\Users\mdt51\AppData\Roaming\npm\node_modules\udacimak\node_modules\execa\lib\error.js:56:11)
    at handlePromise (C:\Users\mdt51\AppData\Roaming\npm\node_modules\udacimak\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by MdTalhaZubayer** [comment]
I have got the solution myself. there are 2 cases here... in 1st case you have to update the youtube-dl.exe a replace it to 

"C:\Users\blablabla\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin\youtube-dl.exe" 


and in my case what is the second one you have to reinstall or install Microsoft visual c++ 2010 redistributable package (x64) and Microsoft visual c++ 2010 redistributable package (x86) both.

I hope it will solve everyone's problems like mine.
