### ISSUE TITLE
error when requesting list of NDs with listnd

### ISSUE THREAD

**Issue by stefanheyer** [udacimak/udacimak#113]
udacimak version 1.6.0

thank you in advance for feedback

when I run:

udacimak listnd

I get:

⠴ Fetch user information via Udacity API2020-04-07T12:52:25.759Z [error]: uncaughtException: Unexpected token a in JSON at position 0
SyntaxError: Unexpected token a in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/__/stefan.heyer/.nvm/versions/node/v13.9.0/lib/node_modules/udacimak/lib/api/fetchApiUdacityGraphql.js:53:30)
    at Request.self.callback (/home/__/stefan.heyer/.nvm/versions/node/v13.9.0/lib/node_modules/udacimak/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (/home/__/stefan.heyer/.nvm/versions/node/v13.9.0/lib/node_modules/udacimak/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:321:20)
    at IncomingMessage.<anonymous> (/home/__/stefan.heyer/.nvm/versions/node/v13.9.0/lib/node_modules/udacimak/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:427:28)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1201:12)
2020-04-07T12:52:25.761Z [error]: Uncaught Exception:
SYNTAXERROR: Unexpected token a in JSON at position 0
STACK: SyntaxError: Unexpected token a in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/__/stefan.heyer/.nvm/versions/node/v13.9.0/lib/node_modules/udacimak/lib/api/fetchApiUdacityGraphql.js:53:30)
    at Request.self.callback (/home/__/stefan.heyer/.nvm/versions/node/v13.9.0/lib/node_modules/udacimak/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (/home/__/stefan.heyer/.nvm/versions/node/v13.9.0/lib/node_modules/udacimak/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:321:20)
    at IncomingMessage.<anonymous> (/home/__/stefan.heyer/.nvm/versions/node/v13.9.0/lib/node_modules/udacimak/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:427:28)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1201:12)

**Comment by stefanheyer** [comment]
btw... I get the same error when trying to download anything with "udacimak download nd***"

**Comment by 1871vinayak** [comment]
@stefanheyer 
 Could you please send me the `Udacity authentication token` to sk20011999@gmail.com or in the reply box so that i can test it on my workspace for the above stated issue..


You can get the ` Udacity authentication token ` by visiting the link below 👇  and following the steps:
https://github.com/udacimak/udacimak/wiki/How-to-Use#settoken-set-udacity-authentication-token

**Comment by stefanheyer** [comment]
@1871vinayak thank you for the quick response. While you were responding I figured that my token probably expired. I am currently resetting it and will check if this resolves the problem (It probably will). Please be aware of the fact that the Udacity authentication token is strictly personal **can not be shared**. Nevertheless, thank you for the support.

**Comment by stefanheyer** [comment]
Indeed as expected my token had expired. I fixed my issues with `listnd` and `download` by resetting it. Unfortunately, the status 500 error remains unresolved.

**Comment by stefanheyer** [comment]
Indeed as expected, my key had expired. By resetting it I managed to fix my `listnd` and `download` error. Next time I will read the documentation more carefully before opening an issue. My bad :)

**Comment by 1871vinayak** [comment]
@stefanheyer 
I very well know that the Udacity authentication token is strictly personal, As i was trying to help you i needed the JSON files for testing it but according to your first comment you were unable to download the JSON file so i cannot expect it from you so that's why i asked for the Udacity authentication token to rectify the issue.
And from next time make sure you open valid issue with detailed explanation which occur due to any faults or bugs in the program.

**Comment by stefanheyer** [comment]
@1871vinayak will do. Thank you for the feedback and super fast assistance.
