### ISSUE TITLE
can not download nd via

### ISSUE THREAD

**Issue by WoHotan** [udacimak/udacimak#115]
**Describe the bug**
can not download nd via docker command.

**To Reproduce**
1. docker pull udacimak/udacimak
2. docker container run -it -v "$(pwd)/:/downloads" udacimak/udacimak download nd256
3. 2020-04-08T14:49:56.509Z [error]: uncaughtException: Unexpected token < in JSON at position 0
SyntaxError: Unexpected token < in JSON at position 0

```shell
✔ Validate Udacity authentication token via Udacity API
2020-04-08T14:48:13.410Z [info]: Hi Richard Wen . You have successfully saved authentication token locally!
2020-04-08T14:48:13.411Z [info]: Start downloading Nanodegree nd256 from Udacity API
✔ Get Nanodegree nd256 information
2020-04-08T14:48:16.490Z [info]: You're authorized to download version 1.0.0, locale en-us of Nanodegree nd256
2020-04-08T14:49:56.509Z [error]: uncaughtException: Unexpected token < in JSON at position 0
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/lib/api/fetchApiUdacityGraphql.js:53:30)
    at Request.self.callback (/usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
2020-04-08T14:49:56.509Z [error]: Uncaught Exception:
SYNTAXERROR: Unexpected token < in JSON at position 0
STACK: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/lib/api/fetchApiUdacityGraphql.js:53:30)
    at Request.self.callback (/usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
```

**Desktop (please complete the following information):**
 - docker img
 - Udacimak Version: v1.6.2

**Course Information**
 - Nanodegree or Course name: [nd213, nd256]
 - Version: [v1.0.0]
 - Locale: [en-us]

**Comment by udacimak** [comment]
Hi @WoHotan 

I suspect that this might be some issue from inside the Docker image itself. Are you able to try downloading the Nanodegree directly with Node.JS your computer to test if it works? If that's the case I can have a look at the Docker image. Right now it's working on my end so I'm not sure where to start to debug

**Comment by WoHotan** [comment]
I use yarn global add udacimak
Run command `udacimka`,have an ENOENT error:  no such file or directory, open '/Users/wenxunqing/.config/yarn/global/node_modules/youtube-dl/bin/details'
```
udacimak
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/wenxunqing/.config/yarn/global/node_modules/youtube-dl/bin/details'
    at Object.openSync (fs.js:462:3)
    at readFileSync (fs.js:364:35)
    at module.exports (/Users/wenxunqing/.config/yarn/global/node_modules/youtube-dl/lib/get-binary.js:15:30)
    at Object.<anonymous> (/Users/wenxunqing/.config/yarn/global/node_modules/youtube-dl/lib/youtube-dl.js:18:41)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/wenxunqing/.config/yarn/global/node_modules/youtube-dl/bin/details'
```

**Comment by udacimak** [comment]
Could you try with nvm, as well as try on different computers?

**Comment by paapaabdullahm** [comment]
**@WoHotan** Check this new [pam79/udacimak](https://github.com/pam79/udacimak) Docker [image](https://hub.docker.com/repository/docker/pam79/udacimak) out. It works out of the box with the latest and greatest of everything required to run [Udacimak](https://github.com/udacimak/udacimak) on your machine. The only requirement is [Docker](https://www.docker.com/get-started). No need for any hacks - it just works.
