### ISSUE TITLE
Correct Path

### ISSUE THREAD

**Issue by gamingneeds** [udacimak/udacimak#12]
This is just a n00b question but I'm trying to render...

I'm putting "udacimak render _json/Front-End \Web \Developer \Nanodegree \v8.0.0" and it's giving me an error, I'm guessing because I'm not writing the file path correctly.

If someone would be so kind as to help me write the correct path, I'd be most greatful.

Thanks. :/

**Comment by udacimak** [comment]
Hi @gamingneeds 

Are you on Windows?

Please try:

```
udacimak render "_json/Front-End Web Developer Nanodegree v8.0.0"
```

Notice how because the path contains white space characters, I've put the path in double-quotes to escape those white spaces.

**Comment by gamingneeds** [comment]
The response was:

`PS C:\WINDOWS\system32> udacimak render "_json/Front-End Web Developer Nanodegree v8.0.0"
2018-11-23T05:57:27.766Z [error]: ERROR: Path to downloaded Udacity course/Nanodegree doesn't exist.
STACK: Error: Path to downloaded Udacity course/Nanodegree doesn't exist.
    at renderCourse (C:\Users\DGNT\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\renderCourse.js:43:11)`

**Comment by gamingneeds** [comment]
The Response was:

`PS C:\WINDOWS\system32> udacimak render "_json/Front-End Web Developer Nanodegree v8.0.0"
2018-11-23T05:57:27.766Z [error]: ERROR: Path to downloaded Udacity course/Nanodegree doesn't exist.
STACK: Error: Path to downloaded Udacity course/Nanodegree doesn't exist.
    at renderCourse (C:\Users\****\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\renderCourse.js:43:11)`

**Comment by udacimak** [comment]
Hi @gamingneeds 

I was assuming that your terminal working directory is the directory that contains the `_json/Front-End Web Developer Nanodegree v8.0.0` folder.

The working directory you had was `C:\WINDOWS\system32>`, so it is not working because there are no `_json/Front-End Web Developer Nanodegree v8.0.0` folders there.

You need to point the terminal to the folder containing the `_json` folder or simply starts a new terminal from the folder containing `_json`

**Comment by gamingneeds** [comment]
I was using "_json" as I saw it in the example. As soon as I removed that used quotes, it rendered properly.

**Comment by gamingneeds** [comment]
I tried that and I receive this:

`PS C:\WINDOWS\system32> udacimak render "Front-End Web Developer Nanodegree v8.0.0"
2018-11-23T06:30:47.842Z [info]: Image already exists. Skip downloading C:\WINDOWS\system32\Front-End Web Developer Nanodegree v8.0.0\img\front-end-large.jpg
2018-11-23T06:30:47.864Z [info]: Completed rendering Nanodegree summary file C:\WINDOWS\system32\Front-End Web Developer Nanodegree v8.0.0/index.html
2018-11-23T06:30:47.866Z [info]: ____________________

2018-11-23T06:30:47.868Z [error]: ERROR: ENOENT: no such file or directory, open 'Front-End Web Developer Nanodegree v8.0.0\assets\css\fonts\data.json'
CODE: ENOENT
STACK: Error: ENOENT: no such file or directory, open 'Front-End Web Developer Nanodegree v8.0.0\assets\css\fonts\data.json'
    at Object.openSync (fs.js:451:3)
    at Object.readFileSync (fs.js:351:35)
    at writeHtmlLesson (C:\Users\****\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\writeHtmlLesson.js:38:26)
    at renderCourse (C:\Users\****\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\renderCourse.js:115:45)`

It says at the top it completed, but is there a way to check if that's actually true since it timed out?

**Comment by gamingneeds** [comment]
It's definitely not completed as most of the links I'm clicking in the index.html are going to File Not Found pages.

**Comment by udacimak** [comment]
Basically, we should not modify the downloaded folder. After downloading, we should render it in a different target folder.

If you have rendered before, you can re-render it. I don't think you have messed up the render data. But you can delete it and render again if wanted.
