### ISSUE TITLE
Latest version keeps crashing

### ISSUE THREAD

**Issue by pranjalchaubey** [udacimak/udacimak#123]
**Describe the bug**
I updated the Udacimak to the latest version. 
Getting this error for any command I use, 
```
C:\Users\username\AppData\Roaming\npm\node_modules\udacimak\node_modules\fs-extra\lib\mkdirs\make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\udacimak\node_modules\fs-extra\lib\mkdirs\index.js:3:44)
```

**To Reproduce**
1. updated Udacimak using the regular command `npm install -g udacimak`

**Expected behavior**
I expected Udacimak to 'work'.

**Udacimak Log**
No LOGs. It's not even getting started. Every command is throwing this error including `udacimak listnd` and `udacimak --version`. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node version: v8.9.3
 - npm version: v6.9.0
 - Udacimak Version: Getting the same error as above
 - Browser: Chrome

**Course Information**
 - Nanodegree or Course name: Data Structures and Algorithms ND
 - Version: Dont know 
 - Locale: en-us

**Comment by udacimak** [comment]
Can you try updating Node JS to the latest version?

**Comment by pranjalchaubey** [comment]
Everything worked just fine after updating to the latest node version. 
Thanks!
