### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by nchand** [udacimak/udacimak#128]
Installed udacimak using `sudo npm install -g udacimak --unsafe-perm=true --allow-root`

which installed :

Downloaded youtube-dl 2020.03.24
+ udacimak@1.6.2

     `udacimak login` produced the following error. 
    /usr/lib/node_modules/udacimak/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

     SyntaxError: Unexpected token {
     at createScript (vm.js:80:10)
     at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/udacimak/node_modules/fs-extra/lib/mkdirs/index.js:3:44)

Any possible solution to fix this?

**Comment by udacimak** [comment]
Please try updating Node JS and Npm to the latest version

**Comment by nchand** [comment]
Updated npm and node to the latest solved the issue. 

Works like a charm! Thanks, @udacimak :+1:
