### ISSUE TITLE
Unable to Invoke udacimak [error]: uncaughtException: Must use import to load ES Module:

### ISSUE THREAD

**Issue by zhanwenchen** [udacimak/udacimak#129]
**Describe the bug**

**To Reproduce**
Doing anything with udacimak, including udacimak --version

**Expected behavior**
Download my nd like I could in 1.6.0.

**Udacimak Log**
Relevant portion of the logs from `udacimak.info.log`
and/or `udacimak.error.log` files:

```shell
udacimak --version                   
2020-04-25T15:20:25.110Z [error]: uncaughtException: Must use import to load ES Module: /Users/my_username/.npm-global/lib/node_modules/udacimak/node_modules/is-promise/index.js
require() of ES modules is not supported.
require() of /Users/my_username/.npm-global/lib/node_modules/udacimak/node_modules/is-promise/index.js from /Users/my_username/.npm-global/lib/node_modules/udacimak/node_modules/run-async/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /Users/my_username/.npm-global/lib/node_modules/udacimak/node_modules/is-promise/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/my_username/.npm-global/lib/node_modules/udacimak/node_modules/is-promise/package.json.

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/my_username/.npm-global/lib/node_modules/udacimak/node_modules/is-promise/index.js
require() of ES modules is not supported.
require() of /Users/my_username/.npm-global/lib/node_modules/udacimak/node_modules/is-promise/index.js from /Users/my_username/.npm-global/lib/node_modules/udacimak/node_modules/run-async/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /Users/my_username/.npm-global/lib/node_modules/udacimak/node_modules/is-promise/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/my_username/.npm-global/lib/node_modules/udacimak/node_modules/is-promise/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1172:13)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/my_username/.npm-global/lib/node_modules/udacimak/node_modules/run-async/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Node version: v12.16.2
 - npm version: 6.14.4
 - Udacimak Version: 1.6.2
 - Browser: Chrome

**Course Information**
N/A

**Additional context**
Just upgraded udacimak from 1.6.0 to 1.6.2. It worked ok in 1.6.0 (except for some video download issues)

**Comment by zhanwenchen** [comment]
This may be an issue with the `esm` (ECMAScript) module change introduced in Node 12.16.x

**Comment by zhanwenchen** [comment]
To fix this issue, go to the package.json and change the "type" (top level) from `module` to `commonjs`.
