### ISSUE TITLE
Failed to Download YouTube Video Error in 1.6.3

### ISSUE THREAD

**Issue by lightc786** [udacimak/udacimak#137]
**Describe the bug**
Udacimak tries to download YouTube videos but ultimately fails. 

**To Reproduce**
Use 1.6.3 to download the UX Design course.

**Expected behavior**
Either YouTube quality 22 or 18 would download successfully but neither are able to download.

**Udacimak Log**
✖ Getting Youtube video (id=O7ZicYcw18c) information with quality=22
2020-05-01T09:22:35.398Z [error]: Failed to download youtube video with id O7ZicYcw18c with quality=22, retrying with quality=18
✖ Getting Youtube video (id=O7ZicYcw18c) information with quality=18
✖ Getting Youtube video (id=astqvK5gB5w) information with quality=22
2020-05-01T09:22:39.051Z [error]: Failed to download youtube video with id astqvK5gB5w with quality=22, retrying with quality=18
✖ Getting Youtube video (id=astqvK5gB5w) information with quality=18
✖ Getting Youtube video (id=Z4O7dgt5E5I) information with quality=22
2020-05-01T09:22:42.735Z [error]: Failed to download youtube video with id Z4O7dgt5E5I with quality=22, retrying with quality=18
✖ Getting Youtube video (id=Z4O7dgt5E5I) information with quality=18
✖ Getting Youtube video (id=To_E_O3COJ4) information with quality=22
2020-05-01T09:22:46.248Z [error]: Failed to download youtube video with id To_E_O3COJ4 with quality=22, retrying with quality=18
✖ Getting Youtube video (id=To_E_O3COJ4) information with quality=18
2020-05-01T09:22:48.549Z [info]: Completed rendering lesson file render/User Experience Nanodegree v1.0.0/Part 05-Module 01-Lesson 01_Portfolio Basics/06. Anatomy of a Portfolio Key Components.html

**Desktop (please complete the following information):**
Docker udacimak 1.6.3 image

**Course Information**
 - User Experience Nanodegree v1.0.0

**Comment by udacimak** [comment]
Could you run Udacimak with `--verbose` command and post the terminal log again? I didn't make any changes to the Youtube video quality, so I'm not sure why it's failing

**Comment by lightc786** [comment]
I added --verbose but not sure it gives any additional info. See below

```
✖ Getting Youtube video (id=F5xQMIOCGs4) information with quality=22
2020-05-01T09:46:29.347Z [error]: Failed to download youtube video with id F5xQMIOCGs4 with quality=22, retrying with quality=18
✖ Getting Youtube video (id=F5xQMIOCGs4) information with quality=18
2020-05-01T09:46:33.651Z [info]: Completed rendering lesson file render/User Experience Nanodegree v1.0.0/Part 04-Module 01-Lesson 03_Building Interactive Designs/08. Figma - Call to Action.html
2020-05-01T09:46:33.651Z [info]: ____________________

✖ Getting Youtube video (id=kpAAwCewgOg) information with quality=22
2020-05-01T09:46:36.763Z [error]: Failed to download youtube video with id kpAAwCewgOg with quality=22, retrying with quality=18
✖ Getting Youtube video (id=kpAAwCewgOg) information with quality=18
2020-05-01T09:46:39.943Z [info]: Completed rendering lesson file render/User Experience Nanodegree v1.0.0/Part 04-Module 01-Lesson 03_Building Interactive Designs/09. Exercise Optimize Engagement.html
2020-05-01T09:46:39.943Z [info]: ____________________

✖ Getting Youtube video (id=ISIimZh63gk) information with quality=22
2020-05-01T09:46:44.176Z [error]: Failed to download youtube video with id ISIimZh63gk with quality=22, retrying with quality=18
✖ Getting Youtube video (id=ISIimZh63gk) information with quality=18
2020-05-01T09:46:49.682Z [info]: Completed rendering lesson file render/User Experience Nanodegree v1.0.0/Part 04-Module 01-Lesson 03_Building Interactive Designs/10. Building a Style Guide.html
2020-05-01T09:46:49.682Z [info]: ____________________

✖ Getting Youtube video (id=0A6Sv9Yv2EY) information with quality=22
2020-05-01T09:46:53.560Z [error]: Failed to download youtube video with id 0A6Sv9Yv2EY with quality=22, retrying with quality=18
✖ Getting Youtube video (id=0A6Sv9Yv2EY) information with quality=18
2020-05-01T09:46:56.713Z [info]: Completed rendering lesson file render/User Experience Nanodegree v1.0.0/Part 04-Module 01-Lesson 03_Building Interactive Designs/11. Exercise Style Guide.html
2020-05-01T09:46:56.713Z [info]: ____________________

✖ Getting Youtube video (id=ghwiekxIDVU) information with quality=22
2020-05-01T09:47:00.819Z [error]: Failed to download youtube video with id ghwiekxIDVU with quality=22, retrying with quality=18
✖ Getting Youtube video (id=ghwiekxIDVU) information with quality=18
✖ Getting Youtube video (id=lXnjpqjttPc) information with quality=22
2020-05-01T09:47:09.218Z [error]: Failed to download youtube video with id lXnjpqjttPc with quality=22, retrying with quality=18
✖ Getting Youtube video (id=lXnjpqjttPc) information with quality=18
2020-05-01T09:47:12.946Z [info]: Completed rendering lesson file render/User Experience Nanodegree v1.0.0/Part 04-Module 01-Lesson 03_Building Interactive Designs/12. Building a UI Kit with Zeplin.html
2020-05-01T09:47:12.946Z [info]: ____________________

✖ Getting Youtube video (id=ermsza_PUmo) information with quality=22
2020-05-01T09:47:16.360Z [error]: Failed to download youtube video with id ermsza_PUmo with quality=22, retrying with quality=18
✖ Getting Youtube video (id=ermsza_PUmo) information with quality=18
✖ Getting Youtube video (id=jLBmB59MLzE) information with quality=22
2020-05-01T09:47:25.819Z [error]: Failed to download youtube video with id jLBmB59MLzE with quality=22, retrying with quality=18
✖ Getting Youtube video (id=jLBmB59MLzE) information with quality=18
2020-05-01T09:47:28.644Z [info]: Completed rendering lesson file render/User Experience Nanodegree v1.0.0/Part 04-Module 01-Lesson 03_Building Interactive Designs/13. Adding Interactivity in Figma.html
2020-05-01T09:47:28.644Z [info]: ____________________

✖ Getting Youtube video (id=8SqlFbPf_ic) information with quality=22
2020-05-01T09:47:33.514Z [error]: Failed to download youtube video with id 8SqlFbPf_ic with quality=22, retrying with quality=18
✖ Getting Youtube video (id=8SqlFbPf_ic) information with quality=18
2020-05-01T09:47:36.321Z [info]: Completed rendering lesson file render/User Experience Nanodegree v1.0.0/Part 04-Module 01-Lesson 03_Building Interactive Designs/14. Exercise Creating a High-Fidelity Screen.html
2020-05-01T09:47:36.322Z [info]: ____________________

```

**Comment by udacimak** [comment]
Could you try updating Udacimak and `render` again? I'm really not sure why it's not downloading for some users so I'm doing an experiment tweak.

**Comment by lightc786** [comment]
Got a new error this time as it didnt get to finish iterating through all the material. See below

`
2020-05-01T10:32:47.432Z [error]: uncaughtException: EIO: i/o error, close
Error: EIO: i/o error, close
2020-05-01T10:32:47.433Z [error]: Uncaught Exception:
ERROR: EIO: i/o error, close
CODE: EIO
STACK: Error: EIO: i/o error, close
`

`
✖ Getting Youtube video (id=YeQN3koywZ0) information with quality=22
2020-05-01T09:23:31.150Z [error]: Failed to download youtube video with id YeQN3koywZ0 with quality=22, retrying with quality=18
✖ Getting Youtube video (id=YeQN3koywZ0) information with quality=18
2020-05-01T09:23:33.099Z [info]: Completed rendering lesson file render/User Experience Nanodegree v1.0.0/Part 05-Module 01-Lesson 02_Building a Starter Portfolio/04. Building Your Starter Portfolio Finalizing Your Case Study.html
2020-05-01T09:23:33.099Z [info]: ____________________

✖ Getting Youtube video (id=oB-Ce6Ef6R4) information with quality=22
2020-05-01T09:23:34.689Z [error]: Failed to download youtube video with id oB-Ce6Ef6R4 with quality=22, retrying with quality=18
✖ Getting Youtube video (id=oB-Ce6Ef6R4) information with quality=18
2020-05-01T09:23:36.799Z [info]: Completed rendering lesson file render/User Experience Nanodegree v1.0.0/Part 05-Module 01-Lesson 02_Building a Starter Portfolio/05. Building Your Starter Portfolio Preparing Your Content.html
2020-05-01T09:23:36.799Z [info]: ____________________

✖ Getting Youtube video (id=X07B-tAoaKU) information with quality=22
2020-05-01T09:23:38.621Z [error]: Failed to download youtube video with id X07B-tAoaKU with quality=22, retrying with quality=18
✖ Getting Youtube video (id=X07B-tAoaKU) information with quality=18
2020-05-01T09:23:40.689Z [info]: Completed rendering lesson file render/User Experience Nanodegree v1.0.0/Part 05-Module 01-Lesson 02_Building a Starter Portfolio/06. Building Your Starter Portfolio Building Your Case Study.html
2020-05-01T09:23:40.689Z [info]: ____________________

✖ Getting Youtube video (id=o5o8eT4o2-Y) information with quality=22
2020-05-01T09:23:42.374Z [error]: Failed to download youtube video with id o5o8eT4o2-Y with quality=22, retrying with quality=18
✖ Getting Youtube video (id=o5o8eT4o2-Y) information with quality=18
2020-05-01T09:23:44.505Z [info]: Completed rendering lesson file render/User Experience Nanodegree v1.0.0/Part 05-Module 01-Lesson 02_Building a Starter Portfolio/07. Building Your Starter Portfolio Final Checks & Publishing.html
2020-05-01T09:23:44.505Z [info]: ____________________

✖ Getting Youtube video (id=cxfvv_ML-6w) information with quality=22
2020-05-01T09:23:46.377Z [error]: Failed to download youtube video with id cxfvv_ML-6w with quality=22, retrying with quality=18
✖ Getting Youtube video (id=cxfvv_ML-6w) information with quality=18
2020-05-01T09:23:48.254Z [info]: Completed rendering lesson file render/User Experience Nanodegree v1.0.0/Part 05-Module 01-Lesson 02_Building a Starter Portfolio/08. Maintaining Your Portfolio Designing For The Portfolio Experience.html
2020-05-01T09:23:48.254Z [info]: ____________________

✖ Getting Youtube video (id=hs5v1-wOPz4) information with quality=22
2020-05-01T09:23:50.106Z [error]: Failed to download youtube video with id hs5v1-wOPz4 with quality=22, retrying with quality=18
✖ Getting Youtube video (id=hs5v1-wOPz4) information with quality=18
2020-05-01T09:23:51.965Z [info]: Completed rendering lesson file render/User Experience Nanodegree v1.0.0/Part 05-Module 01-Lesson 02_Building a Starter Portfolio/09. Maintaining Your Portfolio Adding, Updating, and Archiving Case Studies.html
2020-05-01T09:23:51.965Z [info]: ____________________

✖ Getting Youtube video (id=RKYU9GIWmrI) information with quality=22
2020-05-01T09:23:53.641Z [error]: Failed to download youtube video with id RKYU9GIWmrI with quality=22, retrying with quality=18
✖ Getting Youtube video (id=RKYU9GIWmrI) information with quality=18
2020-05-01T09:23:55.746Z [info]: Completed rendering lesson file render/User Experience Nanodegree v1.0.0/Part 05-Module 01-Lesson 02_Building a Starter Portfolio/10. Maintaining Your Portfolio Reflecting as a Regular Portfolio Practice.html
2020-05-01T09:23:55.746Z [info]: ____________________

`

**Comment by udacimak** [comment]
I think you're still running `v1.6.3`, could you make sure the version is `v1.6.4`?

**Comment by annaszalkiewicz** [comment]
Well I updated Udacimak, downloaded and rendered nanodegree again and still getting video error
![Screenshot from 2020-05-01 13-35-10](https://user-images.githubusercontent.com/34352303/80802889-0524ee00-8bb1-11ea-9810-bf143acd7baf.png)

**Comment by udacimak** [comment]
I'm not sure why it's not working on your end yet - I've tested on both Windows and Ubuntu and they both work. The Youtube download feature seems to be a nightmare 😞 

I've released another update (!!) - `v1.6.6` to try to show more error messages with Youtube download. Could you please also try running with `--verbose` parameter?

**Comment by annaszalkiewicz** [comment]
Udacimak 1.6.6
![Screenshot from 2020-05-01 15-25-27](https://user-images.githubusercontent.com/34352303/80808701-59839a00-8bc0-11ea-9940-fe4489cd4cac.png)

**Comment by z99z** [comment]
I have the same issue
<img width="1036" alt="sc" src="https://user-images.githubusercontent.com/51459119/80813590-eaba3700-8be7-11ea-9c07-a376babbcdf0.png">

**Comment by abbhinavsri30** [comment]
Any updates on this? Getting the same err. 
Using Udacimak 1.6.6

**Comment by tarmole** [comment]
I had also same problem. 
Using windows subsystem for linux
Tried to download same video from command line and got error:
> /usr/bin/env ‘python’ no such file or directory ubuntu 

> 

Found [Youtube-dl: Python not found (18.04)](https://askubuntu.com/questions/1037666/youtube-dl-python-not-found-18-04)
`$ sudo ln -s /usr/bin/python3 /usr/local/bin/python`
It worked for me. Now getting all videos with best quality.

**Comment by udacimak** [comment]
> Any updates on this? Getting the same err.
> Using Udacimak 1.6.6

I'm not sure how to solve this issue yet as I can't replicate the issue on my end. I'm also considering re-writing this module to avoid using `youtube-dl`. I'm also pretty busy at the moment so I'll need to come back to this in the next few weeks.

**Comment by abbhinavsri30** [comment]
> I had also same problem.
> Using windows subsystem for linux
> Tried to download same video from command line and got error:
> 
> > /usr/bin/env ‘python’ no such file or directory ubuntu
> 
> > 
> 
> Found [Youtube-dl: Python not found (18.04)](https://askubuntu.com/questions/1037666/youtube-dl-python-not-found-18-04)
> `$ sudo ln -s /usr/bin/python3 /usr/local/bin/python`
> It worked for me. Now getting all videos with best quality.

@tarmole Can you please explain the steps which resolved the issue for you?

**Comment by annaszalkiewicz** [comment]
After reading @tarmole post I've checked youtube-dl version and got this error:

`anna@anna-VirtualBox:~$ youtube-dl -v`
`/usr/bin/env: ‘python’: No such file or directory`

I run this command:
`$ sudo ln -s /usr/bin/python3 /usr/local/bin/python`

Checked again youtube-dl version and this time I got these results:

> `anna@anna-VirtualBox:~$ youtube-dl -v
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['-v']
> [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
> [debug] youtube-dl version 2020.03.24
> [debug] Python version 3.8.2 (CPython) - Linux-5.4.0-28-generic-x86_64-with-glibc2.29
> [debug] exe versions: none
> [debug] Proxy map: {}
> Usage: youtube-dl [OPTIONS] URL [URL...]

`

Then I rendered nanodegree content:
`$ udacimak render 'React v5.0.0' --targetdir react`

This time I was able to download the content with all videos.
![Screenshot from 2020-05-03 20-31-31](https://user-images.githubusercontent.com/34352303/80922405-30f4cf00-8d7d-11ea-83f3-fe1ba3186b2a.png)

**Comment by abbhinavsri30** [comment]
Awesome, this works at my end too.

Thanks a ton, @tarmole @annaszalkiewicz @udacimak

**Comment by udacimak** [comment]
@lightc786 Does the solution above resolve the issue on your end?

**Comment by abbhinavsri30** [comment]
Yes, it does resolve. I experienced some videos not getting downloaded but the ration was 95:5, 95% got downloaded.

Note: Using Udacimak 1.6.6

**Comment by lightc786** [comment]
Yes, the latest 1.6.6 docker works fine for me. I'm not 100% sure but I actually think one of my errors with the UX course may have been due to getting banned for downloading too much from YouTube. 

Quick question, are there any changes in the html files generated between 1.6.2 and 1.6.6?

Thanks so much for your support!

**Comment by udacimak** [comment]
Thanks for letting me know.

Yes there's a change in HTML in v1.6.3 to fix issue #107

**Comment by christien12** [comment]
@annaszalkiewicz 

> After reading @tarmole post I've checked youtube-dl version and got this error:
> 
> `anna@anna-VirtualBox:~$ youtube-dl -v`
> `/usr/bin/env: ‘python’: No such file or directory`
> 
> I run this command:
> `$ sudo ln -s /usr/bin/python3 /usr/local/bin/python`
> 
> Checked again youtube-dl version and this time I got these results:
> 
> > `anna@anna-VirtualBox:~$ youtube-dl -v
> > [debug] System config: []
> > [debug] User config: []
> > [debug] Custom config: []
> > [debug] Command-line args: ['-v']
> > [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
> > [debug] youtube-dl version 2020.03.24
> > [debug] Python version 3.8.2 (CPython) - Linux-5.4.0-28-generic-x86_64-with-glibc2.29
> > [debug] exe versions: none
> > [debug] Proxy map: {}
> > Usage: youtube-dl [OPTIONS] URL [URL...]
> 
> `
> 
> Then I rendered nanodegree content:
> `$ udacimak render 'React v5.0.0' --targetdir react`
> 
> This time I was able to download the content with all videos.
> ![Screenshot from 2020-05-03 20-31-31](https://user-images.githubusercontent.com/34352303/80922405-30f4cf00-8d7d-11ea-83f3-fe1ba3186b2a.png)

I tried what worked for you but it did not work for me, I am expriencing same issue, some videos downloaded but some did not

![Error](https://user-images.githubusercontent.com/63934082/81435622-185f2d00-9160-11ea-8dbb-dc29d5faae41.JPG)

**Comment by cipheraxat** [comment]
Hey @udacimak please help me to get through this!


(base) akshat@akshat-Inspiron-5570:~$ sudo udacimak login
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/bin/details'
    at Object.openSync (fs.js:443:3)
    at readFileSync (fs.js:343:35)
    at module.exports (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/get-binary.js:15:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/youtube-dl.js:18:41)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)

**Comment by MaoJian-a** [comment]
Hello,i have difficult when i download Youtube videos,how can i add '--proxy 127.0.0.1:1080' after  youtube-dl in render instuction. For example,'youtube-dl --proxy 127.0.0.1:1080 https://www.youtube.com/watch?v=AhGjPmKGMUw'.

**Comment by amitashnanda** [comment]
Hi, I was getting the same error in Linux, Ubuntu 18. I. I upgraded youtube_dl and It worked.

**Comment by RoniFinTech** [comment]
I download youtube-dl but still can't download youtube videos. 
I'm on 1.6.6 udacimak

**Comment by RoniFinTech** [comment]
what worked for me.
did 'brew install python' even though I already had Python installed and then followed the instructions that worked for everybody else.

**Comment by miy001** [comment]
Hi @udacimak ,

It was working back in **August**. Now, youtube-dl seems to fail. Do I need to replace the module? How do I upgrade it? Thanks

**Windows 10**
C:\Users\Admin>udacimak --version
**v1.6.6**

λ npm list -g youtube-dl
C:\Users\Admin\AppData\Roaming\npm
-- udacimak@1.6.6
  -- **youtube-dl@3.0.2**


× Getting Youtube video (id=ZwMY5rAAd7Q) information with quality="22"
2020-12-30T18:25:26.865Z [error]: Failed to download youtube video with id ZwMY5rAAd7Q with quality="22", retrying with quality="18"
× Getting Youtube video (id=ZwMY5rAAd7Q) information with quality="18"
2020-12-30T18:25:29.674Z [error]: Failed to download youtube video with id ZwMY5rAAd7Q with quality="18", retrying with quality=""
× Getting Youtube video (id=ZwMY5rAAd7Q) information with quality=""
2020-12-30T18:25:32.774Z [error]: Youtube video with id ZwMY5rAAd7Q could not be downloaded available. The CLI will ignore this error and skip this download. Please check this error message:

"Command failed with exit code 1: C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\udacimak\\node_modules\\youtube-dl\\bin\\youtube-dl.exe --dump-json -f best --encoding utf8 http://www.youtube.com/watch?v=ZwMY5rAAd7Q"

**Comment by miy001** [comment]
Fixed on Windows 10 :

- Download the latest https://yt-dl.org/latest/youtube-dl.exe
https://github.com/ytdl-org/youtube-dl#installation

- Go to C:\Users\Admin\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin\
Backup youtube-dl.exe in a temp folder and put the latest youtube-dl.exe

**Comment by christien12** [comment]
> Fixed on Windows 10 :
> 
> * Download the latest https://yt-dl.org/latest/youtube-dl.exe
>   https://github.com/ytdl-org/youtube-dl#installation
> * Go to C:\Users\Admin\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin
>   Backup youtube-dl.exe in a temp folder and put the latest youtube-dl.exe

Tried it not work

**Comment by mdsiraj1992** [comment]
Install microsoft visual C++ 2010 (https://www.microsoft.com/en-US/download/details.aspx?id=5555) and then install youtube-dl.exe file

**Comment by eaua9** [comment]
**Problem. Notice two different versions of `youtube-dl`.**

`/usr/local/bin/youtube-dl --version`
202**1.01.16**

`/usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl --version
`202**0.05.03**

**Solution. Copy `youtube-dl` to the path `udacimak` looks for.**

`cp /usr/local/bin/youtube-dl /usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl
`

`/usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl --version`
2021.01.16

**Now it works.**

Please thumbs up this post if it's useful. Thanks.

**Comment by christien12** [comment]
Thank you, it works.

**Comment by romanramirez** [comment]
Experiencing this problem on MacOS. All working fine until executing `udacimak render ...` then it returns:

```
✖ Getting Youtube video (id=OuUMsNsRQeg) information with quality="22"
2021-05-03T22:55:34.490Z [error]: Failed to download youtube video with id OuUMsNsRQeg with quality="22", retrying with quality="18"
✖ Getting Youtube video (id=OuUMsNsRQeg) information with quality="18"
2021-05-03T22:55:37.194Z [error]: Failed to download youtube video with id OuUMsNsRQeg with quality="18", retrying with quality=""
✖ Getting Youtube video (id=OuUMsNsRQeg) information with quality=""
2021-05-03T22:55:40.165Z [error]: Youtube video with id OuUMsNsRQeg could not be downloaded available. The CLI will ignore this error and skip this download. Please check this error message:

"Command failed with exit code 1: /usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best http://www.youtube.com/watch?v=OuUMsNsRQeg"
2021-05-03T22:55:40.176Z
```

checked youtube-dl version and everything is good, not sure what could be the case? 

Attached sn for reference.
<img width="1223" alt="Screen Shot 2021-05-03 at 5 43 02 PM" src="https://user-images.githubusercontent.com/67122053/116949450-1a56b180-ac37-11eb-940d-486b69ea519b.png">

**Comment by cataxto** [comment]
@eaua9 , Did you make this, before o after the sudo ln...?
Tks

**Comment by rajeshroy402** [comment]
Check out #206 
Hope my solution can help you

**Comment by paapaabdullahm** [comment]
Check this [pam79/udacimak](https://github.com/pam79/udacimak) Docker [image](https://hub.docker.com/repository/docker/pam79/udacimak) out. It works out of the box with the latest and greatest of everything required to run [Udacimak](https://github.com/udacimak/udacimak) on your machine. The only requirement is [Docker](https://www.docker.com/get-started). No need for any hacks - it just works.

**Comment by surajy93** [comment]
Windows 10 Fix: 

visit on this site http://ytdl-org.github.io/youtube-dl/download.html and install Microsoft Visual C++ 2010 Service Pack 1 Redistributable Package (x86).

after that replace

Download the latest https://yt-dl.org/latest/youtube-dl.exe
https://github.com/ytdl-org/youtube-dl#installation
Go to C:\Users\Admin\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin
Backup youtube-dl.exe in a temp folder and put the latest youtube-dl.exe

hope this work for you also :) 

![image](https://user-images.githubusercontent.com/42316893/128812667-857dfe4e-0e1c-4287-9c0c-13a47e592e2c.png)

**Comment by schandrachary** [comment]
Hello,

I am a mac user, I am having the same issue. I can render the text files, but there appears to be an issues with youtube downloader. If anyone has reached a solution to this, I would appreciate if you can share. 

```
$ youtube-dl --version
2021.06.06

$ udacimak --version
v1.6.6

$ nvm --version
0.39.0

$ node --version
v16.11.1

$ npm --version
8.0.0
```
<img width="790" alt="Screen Shot 2021-10-18 at 9 49 07 AM" src="https://user-images.githubusercontent.com/8539470/137744795-8f8dd983-6cea-441a-9717-963cc6a65496.png">

I have already tried replacing the latest youtube-dl.exe in udacimak, it appears to make no difference.

**Comment by malnvenshorn** [comment]
I ran into the same issue. Replacing the `youtube-dl` binary in the nodes module doesn't solved it, but invoking `youtube-dl` directly works. So I wrote a little script that parses the `data.json` files and downloads all videos. As a bonus the best available quality can be selected if `ffmpeg` is installed. But make sure it can be merged into a mp4 container otherwise `udacimak` won't skip the video download. Maybe this helps someone.

```
for file in */data.json; do 
    dir=$(dirname "$file")
    num=$(jq ".data.lesson.concepts | length" "$file")
    for i in $(seq 1 $num); do
        for video in "$(jq ".data.lesson.concepts[$(( i - 1 ))] | .atoms[] | select(.video != null)" "$file")"; do
            if [[ -n $video ]]; then
                title=$(echo "$video" | jq -r ".title")
                id=$(echo "$video" | jq -r ".video.youtube_id")
                youtube-dl --download-archive youtube-dl.txt -o "$dir/$(printf '%02d' $i). ${title}-%(id)s.%(ext)s" -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]" https://youtube.com/watch?v=$id
            fi
        done
    done
done
```

**Comment by ericklcl** [comment]
anyone could fix it ?

**Comment by rajeshroy402** [comment]
@ericklcl I am able to use the udacimak terminal. Request you to kindly try with a fresh install

**Comment by peckjon** [comment]
> Check this [pam79/udacimak](https://github.com/pam79/udacimak) Docker [image](https://hub.docker.com/repository/docker/pam79/udacimak) out. It works out of the box with the latest and greatest of everything required to run [Udacimak](https://github.com/udacimak/udacimak) on your machine. The only requirement is [Docker](https://www.docker.com/get-started). No need for any hacks - it just works.

@pam79 **_thank you_** for this image! The library-based fixes were not playing nice with my version of OSX.

Have you / could you submit your changes as a [pull request](https://github.com/udacimak/udacimak/pulls) to this project?

**Comment by peckjon** [comment]
Also, have added a feature request, please upvote if you concur: https://github.com/udacimak/udacimak/issues/219
