### ISSUE TITLE
Not possible to log in

### ISSUE THREAD

**Issue by agutierreza** [udacimak/udacimak#138]
Hi, 

On Ubuntu 18.04.4 LTS, either doing `udacimak settoken <token>` or `udacimak login` I get the following exception:

```
/usr/local/lib/node_modules/udacimak/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/udacimak/node_modules/fs-extra/lib/mkdirs/index.js:3:44)

```

**Comment by udacimak** [comment]
Please update Node to the latest version and retry.

**Comment by agutierreza** [comment]
Thank you, that was it!

**Comment by pra-dan** [comment]
The best way to update is to use
```
nvm install 14.7.0
```
Or follow the steps mentioned here: https://phoenixnap.com/kb/update-node-js-version
