### ISSUE TITLE
Error : ENOENT

### ISSUE THREAD

**Issue by adityapuranik99** [udacimak/udacimak#140]
**Describe the bug**
`Error: ENOENT: no such file or directory, open 'C:\Users\adity\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin\details'`

**Expected behavior**
I just wanted to render some JSON files. This is the first time doing this, I just installed udacimak using `npm install udacimak`, and the installation was completed perfectly/with no errors and I checked in AppData. The folder does **exist**. It is giving me the same error when I ask for version through `udacimak --version`.

```shell
Error: ENOENT: no such file or directory, open 'C:\Users\adity\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin\details'
    at Object.openSync (fs.js:440:3)
    at readFileSync (fs.js:342:35)
    at module.exports (C:\Users\adity\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\get-binary.js:15:30)
    at Object.<anonymous> (C:\Users\adity\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\youtube-dl.js:18:41)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\adity\\AppData\\Roaming\\npm\\node_modules\\udacimak\\node_modules\\youtube-dl\\bin\\details'
}
```

**Screenshots**
![Capture](https://user-images.githubusercontent.com/41595533/81045236-70cdca80-8ed3-11ea-91ce-13032c285340.PNG)
![Capture1](https://user-images.githubusercontent.com/41595533/81045247-77f4d880-8ed3-11ea-844b-079a37d10ae5.PNG)
![Screenshot (19)](https://user-images.githubusercontent.com/41595533/81045399-be4a3780-8ed3-11ea-8389-4d8a0772ce58.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Node version: (`12.14.0`)
 - npm version: (`6.13.4`)
 - Udacimak Version: (`udacimak@1.6.6`)

**Comment by ThatDevCoder** [comment]
Try to use npx. I was having some issues with npm but using npx it fixed it

**Comment by udacimak** [comment]
Could you also try using `yarn` to install, too?

I've had a few weird issues with `youtube-dl` that I cannot replicate.

**Comment by cipheraxat** [comment]
Hey @udacimak please help me to get through this!

(base) akshat@akshat-Inspiron-5570:~$ sudo udacimak login
fs.js:114
throw err;
^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/bin/details'
at Object.openSync (fs.js:443:3)
at readFileSync (fs.js:343:35)
at module.exports (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/get-binary.js:15:30)
at Object. (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/youtube-dl.js:18:41)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Module.require (internal/modules/cjs/loader.js:692:17)

**Comment by INNFINITEMINDS** [comment]
> Try to use npx. I was having some issues with npm but using npx it fixed it

I have installed npx then what should I do ?

**Comment by reachayush** [comment]
![image](https://user-images.githubusercontent.com/33036718/82188694-e42bff00-990b-11ea-9586-37272bc2bb33.png)

I am not getting the "bin" folder in my local machine
OS: Win 10

**Comment by reachayush** [comment]
> Try to use npx. I was having some issues with npm but using npx it fixed it

Could you please tell what needs to be done after installing "npx"

**Comment by Xiangyu-Fu** [comment]
Try to run cmd in administrator mode，and then delete all udacimak files.Use `npm list udacimak` to reinstall udacimak.
