### ISSUE TITLE
Udacimak 1.6.3 crashes on Ubuntu 18.04.4 LTS (on Windows 10 WSL)

### ISSUE THREAD

**Issue by charlyzard** [udacimak/udacimak#153]
**Describe the bug**
The latest udacimak won't run on an Ubuntu 18.04.4 LTS (on Windows 10 WSL) environment.
Even launching udacimak without arguments crashes.
udacimak 1.5.0 was working without problems.

**To Reproduce**
1. On Windows 10
2. Install the Linux Subsystem
3. Install Ubuntu 18.04.4 LTS from the store
4. Install udacimak: sudo npm install -g udacimak
5. Run udacimak without arguments
6. See shell log below

**Expected behavior**
Udacimak should show a list of arguments instead of crashing

**Udacimak Log**
No log files are created

```shell
carlos@DESKTOP-4T041TE:~$ udacimak
/usr/local/lib/node_modules/udacimak/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/udacimak/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS (on Windows 10 WSL)
 - Node version: v8.10.0
 - npm version: 3.5.2
 - Udacimak Version: crashes but it's 1.6.3

**Comment by charlyzard** [comment]
Still happening in version 1.6.6.

**Comment by paapaabdullahm** [comment]
If you can install Ubuntu on VirtualBox with Docker then check this [pam79/udacimak](https://github.com/pam79/udacimak) Docker [image](https://hub.docker.com/repository/docker/pam79/udacimak) out. It works out of the box with the latest and greatest of everything required to run [Udacimak](https://github.com/udacimak/udacimak) on your machine. The only requirement is [Docker](https://www.docker.com/get-started). No need for any hacks - it just works.
