### ISSUE TITLE
Unable to run it throws error

### ISSUE THREAD

**Issue by sachajoy** [udacimak/udacimak#154]
sachajoy@sachajoy:~$ yarn global add udacimak
yarn global v1.22.4
[1/4] Resolving packages...
warning udacimak > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning udacimak > youtube-dl > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning udacimak > npm > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning udacimak > npm > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "udacimak@1.6.6" with binaries:
      - udacimak
Done in 36.99s.
sachajoy@sachajoy:~$ udacimak 
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/bin/details'
    at Object.openSync (fs.js:443:3)
    at readFileSync (fs.js:343:35)
    at module.exports (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/get-binary.js:15:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/youtube-dl.js:18:41)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)

**Comment by tasilva96** [comment]
I have the same issue.. I am using linux ubuntu.

**Comment by chinmaydas96** [comment]
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
Uninstall it.
use this first to set.
then install it again it works for me.

**Comment by paapaabdullahm** [comment]
Check this [pam79/udacimak](https://github.com/pam79/udacimak) Docker [image](https://hub.docker.com/repository/docker/pam79/udacimak) out. It works out of the box with the latest and greatest of everything required to run [Udacimak](https://github.com/udacimak/udacimak) on your machine. The only requirement is [Docker](https://www.docker.com/get-started). No need for any hacks - it just works.

**Comment by 153079019shariq** [comment]
> Check this [pam79/udacimak](https://github.com/pam79/udacimak) Docker [image](https://hub.docker.com/repository/docker/pam79/udacimak) out. It works out of the box with the latest and greatest of everything required to run [Udacimak](https://github.com/udacimak/udacimak) on your machine. The only requirement is [Docker](https://www.docker.com/get-started). No need for any hacks - it just works.

Thanks it works
