### ISSUE TITLE
Udacimak failed to install 

### ISSUE THREAD

**Issue by pra-dan** [udacimak/udacimak#168]
I am trying to install udacimak on Google Collaboratory. I am using the already installed packages and not installing any new package. 

I run 
```
!npm install -g udacimak
```

**Console Log**
Relevant portion of the logs from `udacimak.info.log`
and/or `udacimak.error.log` files:

```shell
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/tools/node/bin/udacimak -> /tools/node/lib/node_modules/udacimak/lib/index.js

> youtube-dl@3.0.2 postinstall /tools/node/lib/node_modules/udacimak/node_modules/youtube-dl
> node ./scripts/download.js

/tools/node/lib/node_modules/udacimak/node_modules/mkdirp/index.js:91
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/tools/node/lib/node_modules/udacimak/node_modules/youtube-dl/bin'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Function.sync (/tools/node/lib/node_modules/udacimak/node_modules/mkdirp/index.js:72:13)
    at createBase (/tools/node/lib/node_modules/udacimak/node_modules/youtube-dl/lib/downloader.js:64:10)
    at downloader (/tools/node/lib/node_modules/udacimak/node_modules/youtube-dl/lib/downloader.js:75:3)
    at Object.<anonymous> (/tools/node/lib/node_modules/udacimak/node_modules/youtube-dl/scripts/download.js:3:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-dl@3.0.2 postinstall: `node ./scripts/download.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the youtube-dl@3.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-20T12_44_50_786Z-debug.log
```

**Comment by capitan-davide** [comment]
I had the same issue in Ubuntu WSL. I solved it following #154. Uninstall, do the procedure and than run (no sudo):
`npm install -g udacimak`

Worked for me, hope it helps.
