### ISSUE TITLE
An invalid URI problem while rendering

### ISSUE THREAD

**Issue by AlainOUYANG** [udacimak/udacimak#17]
I received such problem while rendering, that the program keeps trying to download one gif file but got an "invalid URI" error, so it stays at the download status :
```
⠋ Download media file unnamed-348904-0.gif2019-01-17T22:39:15.528Z [error]: ERROR: Invalid URI "https:///%3Ca%20href="
STACK: Error: Invalid URI "https:///%3Ca%20href="
    at Request.init (/usr/local/lib/node_modules/udacimak/node_modules/request/request.js:273:31)
    at new Request (/usr/local/lib/node_modules/udacimak/node_modules/request/request.js:127:8)
    at request (/usr/local/lib/node_modules/udacimak/node_modules/request/index.js:53:10)
    at Promise (/usr/local/lib/node_modules/udacimak/lib/commands/utils/downloadImage.js:84:56)
    at new Promise (<anonymous>)
    at downloadImage (/usr/local/lib/node_modules/udacimak/lib/commands/utils/downloadImage.js:36:10)
    at downloadMediaInHtml (/usr/local/lib/node_modules/udacimak/lib/commands/utils/downloadMediaInHtml.js:77:53)
    at createHtmlText (/usr/local/lib/node_modules/udacimak/lib/commands/render/functions/utils/createHtmlText.js:19:47)
    at createHtmlTextAtom (/usr/local/lib/node_modules/udacimak/lib/commands/render/functions/atoms/createHtmlTextAtom.js:23:48)
    at writeHtmlConcept (/usr/local/lib/node_modules/udacimak/lib/commands/render/functions/writeHtmlConcept.js:51:53)
⠴ Download media file unnamed-348904-0.gif
⠙ Download media file unnamed-348904-0.gif
⠸ Download media file unnamed-348904-0.gif
⠸ Download media file unnamed-348904-0.gif
```
I am using macOS and trying to download my materials which are in Chinese.
Other contents before were well downloaded but it stops at this gif file and keeps trying.

**Comment by udacimak** [comment]
@AlainOUYANG 
The JSON data is sometimes very "dirty" as it can contain invalid syntax, invalid URL address.
One way to fix this is to check the URL of the image in the relevant `data.json` file and manually change it to be a correct URL.
If you don't know how to do this, please send your downloaded JSON files to udacimak@tutanota.com and I will be able to help 👍

**Comment by AlainOUYANG** [comment]
Yeah, it works! Thanks for your reply!
I really appreciate that and will recommend this awesome tool to my Chinese classmates cos we are informed yesterday that the term has changed.
Btw, the Chinese Udacity Team announced that they will provide a tool for downloading the course "on one click", but didn't mention whether it will be only the videos or all other materials as well.

**Comment by greyhats13** [comment]
I had an issues when the folder contains . (dot), so udacimak can't render the json, and folder cannot be deleted in Windows 10. It occurred when I render the Udacity free course with code ud169 (Udacity - Embedded Systems). Because the folden contain names Lesson "12_P3L2 Energy Opt. Post-pass Reg. Alloc.". I think the udacimak render must filter dot when create a folder.
