### ISSUE TITLE
render command failed 

### ISSUE THREAD

**Issue by Needrom** [udacimak/udacimak#19]
**failed with render**
render command failed while getting youtube video id xxx information

```
✔ Download media file part-header-2.jpg
 ████████████████████████████████████████ 100% | ETA: 0s | 161738/161738
2019-01-24T09:39:29.971Z [info]: Downloaded media file part-header-2.jpg
2019-01-24T09:39:30.004Z [info]: Completed rendering Nanodegree summary file render_dir/深度学习 v2.0.0/index.html
2019-01-24T09:39:30.004Z [info]: ____________________

2019-01-24T09:39:30.034Z [info]: Completed rendering lesson summary file render_dir/深度学习 v2.0.0/Part 01-Module 01-Lesson 01_欢迎学习此课程/index.html
2019-01-24T09:39:30.035Z [info]: ____________________

✔ Download media file celia.png
 ████████████████████████████████████████ 100% | ETA: 0s | 40879/40879
2019-01-24T09:39:30.381Z [info]: Downloaded media file celia.png
2019-01-24T09:39:30.390Z [info]: Completed rendering lesson file render_dir/深度学习 v2.0.0/Part 01-Module 01-Lesson 01_欢迎学习此课程/01. 欢迎.html
2019-01-24T09:39:30.390Z [info]: ____________________

2019-01-24T09:39:30.420Z [info]: Completed rendering lesson file render_dir/深度学习 v2.0.0/Part 01-Module 01-Lesson 01_欢迎学习此课程/02. 优达学城学习社群介绍.html
2019-01-24T09:39:30.421Z [info]: ____________________

2019-01-24T09:39:30.425Z [info]: Image already exists. Skip downloading render_dir/深度学习 v2.0.0/Part 01-Module 01-Lesson 01_欢迎学习此课程/img/celia.png
2019-01-24T09:39:30.447Z [info]: Completed rendering lesson file render_dir/深度学习 v2.0.0/Part 01-Module 01-Lesson 01_欢迎学习此课程/03. 如何加入学习社群.html
2019-01-24T09:39:30.447Z [info]: ____________________

Getting Youtube video id PdPdogFHnvE information
2019-01-24T07:42:07.444Z [error]: ERROR: Command failed: /Users/guoliang/udacity/udacimak/node_modules/youtube-dl/bin/youtube-dl --dump-json --format=best http://www.youtube.com/watch?v=PdPdogFHnvE
ERROR: Unable to download webpage: <urlopen error [Errno 60] Operation timed out> (caused by URLError(TimeoutError(60, 'Operation timed out'),))

CODE: 1
STACK: Error: Command failed: /Users/guoliang/udacity/udacimak/node_modules/youtube-dl/bin/youtube-dl --dump-json --format=best http://www.youtube.com/watch?v=PdPdogFHnvE
ERROR: Unable to download webpage: <urlopen error [Errno 60] Operation timed out> (caused by URLError(TimeoutError(60, 'Operation timed out'),))

    at ChildProcess.exithandler (child_process.js:297:12)
    at ChildProcess.emit (events.js:188:13)
    at maybeClose (internal/child_process.js:978:16)
```

with command ```udacimak render path -t path2```
udacimak version:1.2.2

**Comment by Iijingxin** [comment]
请问这个是怎么解决的？

**Comment by Iijingxin** [comment]
udacimak render path -t path2 改个路径还是不可以呢，youtube视频那里就卡住了

**Comment by musheer491** [comment]
Hi, what is this error representing

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/53042436/82649772-59167600-9c37-11ea-899b-d4c8073b057c.png">
