### ISSUE TITLE
Can't install udacimak: SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by i-tanova** [udacimak/udacimak#197]
**Describe the bug**
When I install it I get error.
> youtube-dl@3.5.0 check /usr/local/lib/node_modules/udacimak/node_modules/youtube-dl
> bin-version-check python '>=2'

┌──────────────────────────────────────────────────────────┐
│                 npm update check failed                  │
│           Try running with sudo or get access            │
│           to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /home/tanova/.config │
└──────────────────────────────────────────────────────────┘

> youtube-dl@3.5.0 download /usr/local/lib/node_modules/udacimak/node_modules/youtube-dl
> node ./scripts/download.js

/usr/local/lib/node_modules/udacimak/node_modules/got/dist/source/create.js:157
    const paginateEach = (async function* (url, options) {
                                        ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/udacimak/node_modules/got/dist/source/index.js:14:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-dl@3.5.0 download: `node ./scripts/download.js`
npm ERR! Exit status 1

**Comment by i-tanova** [comment]
Fixed when I installed node 15

**Comment by rajeshroy402** [comment]
Hi @i-tanova , 
Can you take a look at this issue? : https://github.com/udacimak/udacimak/issues/195
