### ISSUE TITLE
un able to install udacimak

### ISSUE THREAD

**Issue by ahmedtamam721** [udacimak/udacimak#224]
![image](https://user-images.githubusercontent.com/37932386/149773127-24a5bf0c-a019-4a6d-a7f6-92b141572ab4.png)

**Comment by h3sh4m** [comment]
I have the same issue

**Comment by h3sh4m** [comment]
C:\WINDOWS\system32>npm install -g udacimak
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated youtube-dl@3.5.0: node-youtube-dl is deprecated. use `npm.im/youtube-dl-exec` instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path C:\Users\Hesha\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\Hesha\AppData\Local\Temp\postinstall-630ca590.cmd
npm ERR! > youtube-dl@3.5.0 check C:\Users\Hesha\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl
npm ERR! > bin-version-check python '>=2'
npm ERR! Error: Invalid version range
npm ERR!     at module.exports (C:\Users\Hesha\AppData\Roaming\npm\node_modules\udacimak\node_modules\bin-version-check\index.js:12:25)
npm ERR!     at Object.<anonymous> (C:\Users\Hesha\AppData\Roaming\npm\node_modules\udacimak\node_modules\bin-version-check-cli\cli.js:29:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1120:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:998:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:839:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:17:47
npm ERR! npm ERR! code ELIFECYCLE
npm ERR! npm ERR! errno 1
npm ERR! npm ERR! youtube-dl@3.5.0 check: `bin-version-check python '>=2'`
npm ERR! npm ERR! Exit status 1
npm ERR! npm ERR!
npm ERR! npm ERR! Failed at the youtube-dl@3.5.0 check script.
npm ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\Hesha\AppData\Local\npm-cache\_logs\2022-07-24T08_17_45_074Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hesha\AppData\Local\npm-cache\_logs\2022-07-24T08_16_31_803Z-debug-0.log

**Comment by aminpaw** [comment]
same issue

**Comment by davidnwaneri** [comment]
Same here

**Comment by OmarShawky1** [comment]
same

**Comment by asadhayat1068** [comment]
You guys need to install **Python 2.7.x** and should be default version.

**Comment by pradhyuman-yadav** [comment]
You have python as python3 or py.

you can run in docker and use symlink or use an alias.


For Dockerfile
RUN ln -s /usr/bin/python3 /usr/bin/python & \
    ln -s /usr/bin/pip3 /usr/bin/pip

For Alias
echo 'alias python="python3"' >> ~/.zshrc && source;
