### ISSUE TITLE
I can't get any farther from udacimak settoken YOUR_UDACITY_AUTH_TOKEN

### ISSUE THREAD

**Issue by tim11235** [udacimak/udacimak#25]
I can't get any farther when I try to set the token the say command not found but when i start it with sudo I get this 

internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.dirname (path.js:1260:5)
    at Object.<anonymous> (/Users/timikuzwe/.nvm/versions/node/v11.10.1/lib/node_modules/udacimak/node_modules/youtube-dl/lib/youtube-dl.js:21:73)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
Tims-MacBook-Pro:~ timikuzwe$

**Comment by udacimak** [comment]
Please paste the full command that you typed so I can have a look. Thanks.

**Comment by tim11235** [comment]
Tims-MacBook-Pro:~ timikuzwe$ udacimak settoken YOUR_UDACITY_AUTH_TOKEN
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.dirname (path.js:1260:5)
    at Object.<anonymous> (/Users/timikuzwe/.nvm/versions/node/v11.10.1/lib/node_modules/udacimak/node_modules/youtube-dl/lib/youtube-dl.js:21:73)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
Tims-MacBook-Pro:~ timikuzwe$

**Comment by udacimak** [comment]
You need to replace `YOUR_UDACITY_AUTH_TOKEN` with your own JWT token. Please check README on how to get that JWT token from browser cookie.

**Comment by tim11235** [comment]
Tims-MacBook-Pro:~ timikuzwe$ udacimak settoken eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTM2NDk4OTEsImlhdCI6MTU1MTA1Nzg5MSwia2lkIjoibW1yZDQ5ZjJ5IiwidWlkIjoiMTA1OTkyMzg5NzAiLCJyb2xlcyI6WyJ1c2VyIl19.IKrNQQYnes-58c2tgze97wLc_lO4oePu61ZdmVAC8wc8BoG8EWaYHOBfALhV2eB345ZwiR4eJ8TcYcaSTDTKzZPOtc0DSrN402Z1H-HZ8Bxnoeru_glO2ifK7BnNENECCDX9ReJ7q8eghbfpjlDmREIEhMzSZrXyxxqbdYWRVMVQEBDlCwBcm4ETCKpJ1tyfT0j-ezm1uW7VMv_ccwSSp1JIOTiLNrRfR-Fu6FSH-WtLpextHZ_J4bFt2sbdpVfTkVdXKP8dCQxoeDmxYlskKDTpk4yw58ZVuOeAAWwZvZAXHfhlYoCLZtAzPkc2NvXfkDNniimMB87kN4QFmvL6Zw
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.dirname (path.js:1260:5)
    at Object.<anonymous> (/Users/timikuzwe/.nvm/versions/node/v11.10.1/lib/node_modules/udacimak/node_modules/youtube-dl/lib/youtube-dl.js:21:73)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
Tims-MacBook-Pro:~ timikuzwe$

**Comment by udacimak** [comment]
Thanks. There's something wrong with the token string Could you check if there are any accidental spaces in the token when you put in the terminal?

**Comment by tim11235** [comment]
let me check but I don't think so

**Comment by udacimak** [comment]
Sure, I'm not on Mac so I can't check how it behaves in the terminal.

**Comment by tim11235** [comment]
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTM2NDk4OTEsImlhdCI6MTU1MTA1Nzg5MSwia2lkIjoibW1yZDQ5ZjJ5IiwidWlkIjoiMTA1OTkyMzg5NzAiLCJyb2xlcyI6WyJ1c2VyIl19.IKrNQQYnes-58c2tgze97wLc_lO4oePu61ZdmVAC8wc8BoG8EWaYHOBfALhV2eB345ZwiR4eJ8TcYcaSTDTKzZPOtc0DSrN402Z1H-HZ8Bxnoeru_glO2ifK7BnNENECCDX9ReJ7q8eghbfpjlDmREIEhMzSZrXyxxqbdYWRVMVQEBDlCwBcm4ETCKpJ1tyfT0j-ezm1uW7VMv_ccwSSp1JIOTiLNrRfR-Fu6FSH-WtLpextHZ_J4bFt2sbdpVfTkVdXKP8dCQxoeDmxYlskKDTpk4yw58ZVuOeAAWwZvZAXHfhlYoCLZtAzPkc2NvXfkDNniimMB87kN4QFmvL6Zw 

This is what my token looks like.

**Comment by tim11235** [comment]
I used the script to copy it

**Comment by udacimak** [comment]
I can set the token successfully.  Is it possible if you try a different terminal?
