### ISSUE TITLE
uncaughtException: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by heysachin** [udacimak/udacimak#26]
**Describe the bug**
uncaughtException: Unexpected token < in JSON at position 0 when downloading JSON files of self driving car nanodegree

**To Reproduce**
udacimak download nd013 on the terminal

**Expected behavior**
Download the JSON files ready for rendering

```shell
2019-03-09T16:33:49.922Z [error]: uncaughtException: Unexpected token < in JSON at position 0
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/root/.nvm/versions/node/v8.15.1/lib/node_modules/udacimak/lib/api/fetchApiUdacityGraphql.js:53:30)
    at Request.self.callback (/root/.nvm/versions/node/v8.15.1/lib/node_modules/udacimak/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/root/.nvm/versions/node/v8.15.1/lib/node_modules/udacimak/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/root/.nvm/versions/node/v8.15.1/lib/node_modules/udacimak/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
2019-03-09T16:33:49.923Z [error]: Uncaught Exception:
SYNTAXERROR: Unexpected token < in JSON at position 0
STACK: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/root/.nvm/versions/node/v8.15.1/lib/node_modules/udacimak/lib/api/fetchApiUdacityGraphql.js:53:30)
    at Request.self.callback (/root/.nvm/versions/node/v8.15.1/lib/node_modules/udacimak/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/root/.nvm/versions/node/v8.15.1/lib/node_modules/udacimak/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/root/.nvm/versions/node/v8.15.1/lib/node_modules/udacimak/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
```

**Desktop (please complete the following information):**
 - OS:  Ubuntu 18.10
 - Node version: 8.15.1
 - npm version: 6.4.1
 - Udacimak Version: v1.3.0
 - Terminal

**Course Information**
 - nd013 version 2.0.0 (locale: en-us): Self-Driving Car Engineer

**Comment by heysachin** [comment]
The Website Content was down and hence wasn't able to download the JSON content. working perfectly now.
