### ISSUE TITLE
ERROR：connect ETIMEOUT 52.216.84.19:443

### ISSUE THREAD

**Issue by changyuji** [udacimak/udacimak#27]
CODE：ETIMEOUT
STACK：Error： connect ETIMEOUT 52.216.84.19:443
at TcpConnectWrap.afterConnect [as onComplete] (net.js:1097:14)

when i try to render the course deep learning with cmd after a proxy in china , it report the above error
i am using 
windows 8.1 
udacimak 1.3.0 lastest version
npm 6.4.1
node 10.15.3

**Comment by changyuji** [comment]
any one can help me

**Comment by udacimak** [comment]
@changyuji 
Do you have the full error stack log?

Are you using a CDN?

**Comment by changyuji** [comment]
C:\Users\johm>udacimak render A --verbose
2019-03-11T04:06:52.271Z [info]: Completed rendering lesson summary file C:\User
s\johm\A\Lesson 01_Introduction and Xcode\index.html
2019-03-11T04:06:52.280Z [info]: ____________________

\ Getting Youtube video id nsKJe2cfYns information
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--dump-json', '--format=best', '--verbose', '--enco
ding', 'utf8', 'http://www.youtube.com/watch?v=nsKJe2cfYns']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref utf8
[debug] youtube-dl version 2019.03.09
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {'ftp': 'ftp://127.0.0.1:1080', 'http': 'http://127.0.0.1:108
0', 'https': 'https://127.0.0.1:1080'}

× Getting Youtube video id nsKJe2cfYns information
2019-03-11T04:07:44.659Z [error]: ERROR: connect ETIMEDOUT 174.36.196.242:443
CODE: ETIMEDOUT
STACK: Error: connect ETIMEDOUT 174.36.196.242:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)

C:\Users\johm>

/*************************************Above are shortcut after run udacimak render command***********************/

**Comment by changyuji** [comment]
/******************************error from udacimak.error*****************************/

2019-03-11T04:07:44.659Z [[31merror[39m]: ERROR: connect ETIMEDOUT 174.36.196.242:443
CODE: ETIMEDOUT
STACK: Error: connect ETIMEDOUT 174.36.196.242:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)

/******************below come from udacimak.info


2019-03-11T04:04:58.794Z [[32minfo[39m]: Downloaded lesson JSON for C:\Users\johm\Intro to iOS App Development with Swift v1.0.0\Lesson 01_Introduction and Xcode
2019-03-11T04:04:59.754Z [[32minfo[39m]: Downloaded lesson JSON for C:\Users\johm\Intro to iOS App Development with Swift v1.0.0\Lesson 02_AutoLayout and Buttons
2019-03-11T04:05:00.664Z [[32minfo[39m]: Downloaded lesson JSON for C:\Users\johm\Intro to iOS App Development with Swift v1.0.0\Lesson 03_ViewController and Multiple Views
2019-03-11T04:05:01.019Z [[32minfo[39m]: Downloaded lesson JSON for C:\Users\johm\Intro to iOS App Development with Swift v1.0.0\Lesson 04_Delegation and Recording
2019-03-11T04:05:01.365Z [[32minfo[39m]: Downloaded lesson JSON for C:\Users\johm\Intro to iOS App Development with Swift v1.0.0\Lesson 05_Playback and Audio Effects
2019-03-11T04:05:01.681Z [[32minfo[39m]: Downloaded lesson JSON for C:\Users\johm\Intro to iOS App Development with Swift v1.0.0\Lesson 06_Final App Details
2019-03-11T04:05:01.683Z [[32minfo[39m]: Completed downloading Intro to iOS App Development with Swift course's JSON data from Udacity API
2019-03-11T04:05:01.685Z [[32minfo[39m]: ____________________

2019-03-11T04:06:52.271Z [[32minfo[39m]: Completed rendering lesson summary file C:\Users\johm\A\Lesson 01_Introduction and Xcode\index.html
2019-03-11T04:06:52.280Z [[32minfo[39m]: ____________________

2019-03-11T04:07:44.659Z [[31merror[39m]: ERROR: connect ETIMEDOUT 174.36.196.242:443
CODE: ETIMEDOUT
STACK: Error: connect ETIMEDOUT 174.36.196.242:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)

**Comment by changyuji** [comment]
> 
> 
> @changyuji
> Do you have the full error stack log?
> 
> Are you using a CDN?

i am using shadowsocks proxy ,i live in china

**Comment by udacimak** [comment]
Can you try a different CDN?
This is a network connection issue so I can't fix it by updating udacimak.

**Comment by changyuji** [comment]
> Can you try a different CDN?
> This is a network connection issue so I can't fix it by updating udacimak.

i think the problem is it has no way to use the proxy of the system, and the problem will disappear when using a vpn, could you please add a feature to let the program can use my system proxy

**Comment by udacimak** [comment]
@changyuji  
I'm not sure how to achieve that yet and will not likely adding that feature in future updates.

**Comment by banpie** [comment]
> > Can you try a different CDN?
> > This is a network connection issue so I can't fix it by updating udacimak.
> 
> i think the problem is it has no way to use the proxy of the system, and the problem will disappear when using a vpn, could you please add a feature to let the program can use the system proxy

你是通过ss走全局代理来实现的吗？我也是出现了time out的情况。

**Comment by willgiton** [comment]
@banpie @changyuji 你们解决了么？

**Comment by changyuji** [comment]
没下到一半出这个错误后面再也无法继续了重新render也没有用


发自我的iPhone

------------------ Original ------------------
