### ISSUE TITLE
Error Status Code 500 - Unsure how to troubleshoot (skip or re-try)

### ISSUE THREAD

**Issue by as2leung** [udacimak/udacimak#28]
**Describe the bug**
Hi,
 
I am getting this "Error" status code 500, which I don't see any additional information about. This causes the rendering process to stop, and therefore, I am not sure what the best way is to try again from that point onward or how I can skip the file. I have been able to render Parts 1 to 8 of the course without problem so far. Thanks in advance.

**Udacimak Log**

× Getting Youtube video id MUZXLvBI2sw information
2019-03-13T01:47:34.099Z [error]: ERROR: status code 500
STACK: Error: status code 500
    at Request.response (C:\Users\Andrew Leung\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\youtube-dl.js:74:41)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (C:\Users\Andrew Leung\AppData\Roaming\npm\node_modules\udacimak\node_modules\request\request.js:1066:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)

**Screenshots**

![image](https://user-images.githubusercontent.com/48498455/54248285-81bebe00-4512-11e9-938d-7b63b9803685.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64bit
 - Node version: (8.12.0)
 - npm version: (6.4.1)
 - Udacimak Version: (v1.3.0)
 - Browser [Chrome]

**Course Information**
 - Nanodegree or Course name: [Data Analyst Nanodegree]
 - Version: [e.g. v7.0.0]
 - Locale: [e.g. en-can]

**Comment by udacimak** [comment]
It's just some connection issue with the Youtube video.
You can run the same render command again, it'll automatically skip downloaded contents and will only download files that are not downloaded yet.

**Comment by as2leung** [comment]
Thank you! As a follow-up, I tried to render just that specific module and I got the following error:

C:\Users\Andrew Leung\Data Analyst Nanodegree v7.0.0\Part 09_Data Story Telling\Module 01_Data Viz Lessons 2>udacimak render "Lesson 01_Introduction to Data Visualization"
2019-03-13T02:19:37.196Z [error]: TYPEERROR: Cannot read property 'lessons' of undefined
STACK: TypeError: Cannot read property 'lessons' of undefined
    at writeHtmlCourseSummary (C:\Users\Andrew Leung\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\writeHtmlCourseSummary.js:92:66)
    at <anonymous>


Is there anything else that I need to worry about? Or should I just run the overall command: udacimak render "Data Analyst Nanodegree v7.0.0"  and try it from the beginning?

**Comment by udacimak** [comment]
No worries. Yes, you should run the overall command. The parameter passed to `render` command must be the Nanodegree folder (not the lesson or anything else) - so basically just run it the same as when you run it the first time.

**Comment by as2leung** [comment]
That's great to know. I do however run into this error of a missing file when I try to run it again. I don't believe that I've altered any of the files in any way. Any insight would help. Thank you.

C:\Users\Andrew Leung>udacimak render "Data Analyst Nanodegree v7.0.0"
2019-03-13T02:31:32.843Z [info]: Image already exists. Skip downloading C:\Users\Andrew Leung\Data Analyst Nanodegree v7.0.0\img\data-analyst-large.jpg
2019-03-13T02:31:32.905Z [info]: Completed rendering Nanodegree summary file C:\Users\Andrew Leung\Data Analyst Nanodegree v7.0.0/index.html
2019-03-13T02:31:32.905Z [info]: ____________________

2019-03-13T02:31:32.921Z [error]: ERROR: ENOENT: no such file or directory, open 'C:\Users\Andrew Leung\Data Analyst Nanodegree v7.0.0\assets\css\fonts\data.json'
CODE: ENOENT
STACK: Error: ENOENT: no such file or directory, open 'C:\Users\Andrew Leung\Data Analyst Nanodegree v7.0.0\assets\css\fonts\data.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at writeHtmlLesson (C:\Users\Andrew Leung\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\writeHtmlLesson.js:38:26)
    at renderCourse (C:\Users\Andrew Leung\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\renderCourse.js:115:45)
    at <anonymous>

**Comment by udacimak** [comment]
Hi, 

That's because you're rendering into the folder that contains all JSON data files.
So now you should:
- Download the Nanodegree again.
- `cd` into a different directory, then render that downloaded folder.

The _rendered_ content must be separated from the _downloaded_ content.

**Comment by as2leung** [comment]
That makes sense, I will definitely keep them separate now. At this point, I'm just getting the  "Error" status code 500 while trying to render to the new folder following the Nanodegree download. To confirm, I'm guessing I should just wait until later to try running it again? Thanks again for all the help, and for creating such an awesome CLI!

**Comment by udacimak** [comment]
Thanks!

I'm not sure what's causing the 500 code error, but waiting a bit later may help.
