### ISSUE TITLE
Error at the end of rendering

### ISSUE THREAD

**Issue by davidmokos** [udacimak/udacimak#29]
version: v1.3.0

```bash
...
2019-03-22T15:04:50.882Z [info]: Completed rendering lesson file /Users/mokos/Developer/udacity/Deep Learning v6.0.0/Part 09-Module 02-Lesson 01_Introduction to TensorFlow/17. Outro.html
2019-03-22T15:04:50.883Z [info]: ____________________

2019-03-22T15:04:50.884Z [error]: ERROR: ENOENT: no such file or directory, open 'Deep Learning v6.0.0/assets/css/fonts/data.json'
CODE: ENOENT
STACK: Error: ENOENT: no such file or directory, open 'Deep Learning v6.0.0/assets/css/fonts/data.json'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at writeHtmlLesson (/usr/local/lib/node_modules/udacimak/lib/commands/render/functions/writeHtmlLesson.js:38:26)
    at renderCourse (/usr/local/lib/node_modules/udacimak/lib/commands/render/functions/renderCourse.js:115:45)
```

**Comment by udacimak** [comment]
Please read this README section:
- https://github.com/udacimak/udacimak#important-render-directory-note

I think you were rendering into the downloaded folder, hence the error. We should render into a completely different location instead.
