### ISSUE TITLE
Udacimak stops on render of "AI for Trading" nano degree

### ISSUE THREAD

**Issue by rgekhman** [udacimak/udacimak#3]
Unhandled promise rejection error: 

```
C:\...\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib>udacimak render "D:\AI for Trading v1.0.0" --targetdir D:\AI4Trading --verbose
2018-11-06T04:51:03.502Z [info]: Completed rendering Nanodegree summary file D:\AI4Trading/AI for Trading v1.0.0/index.html
2018-11-06T04:51:03.504Z [info]: ----------------------------------------
2018-11-06T04:51:03.519Z [info]: Completed rendering lesson summary file D:\AI4Trading/AI for Trading v1.0.0/Part 01-Module 01-Lesson 01_Welcome to the Nano
degree Program/index.html
2018-11-06T04:51:03.520Z [info]: ----------------------------------------
(node:17640) UnhandledPromiseRejectionWarning: Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at spawn (child_process.js:533:9)
    at execFile (child_process.js:216:15)
    at call (C:\Users\rgekh\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\youtube-dl.js:163:5)
    at Function.getInfo (C:\Users\rgekh\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\youtube-dl.js:285:5)
    at module.exports (C:\Users\rgekh\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\youtube-dl.js:107:10)
    at Promise (C:\Users\rgekh\AppData\Roaming\npm\node_modules\udacimak\lib\commands\utils\downloadYoutube.js:58:42)
    at new Promise (<anonymous>)
    at downloadYoutube (C:\Users\rgekh\AppData\Roaming\npm\node_modules\udacimak\lib\commands\utils\downloadYoutube.js:36:10)
    at Promise (C:\Users\rgekh\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\atoms\createHtmlVideoAtom.js:21:32)
(node:17640) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a c
atch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17640) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminat
e the Node.js process with a non-zero exit code.
```

**Comment by udacimak** [comment]
Please refer to this section of the README:
- https://github.com/udacimak/udacimak#windows-users-and-youtube-dl

For Windows, we need to download `youtube-dl.exe` and replace the default one. Refer to [this `node-youtube-dl` issue](https://github.com/przemyslawpluta/node-youtube-dl/issues/169#issuecomment-380400885)

**Comment by udacimak** [comment]
@rgekhman 
I realized it's not ideal to make every Windows user fix it. Plus the fix needs to be manually done everytime `udacimak` is updated. So I've released a patch.

You can run `npm i -g udacimak` to get the updated version.

Instead of installing `node-youtube-dl` from `npm`, Udacimak now will install `node-youtube-dl` from its new Github commit that fixed this issue.

Please open a new issue if any problems.
