### ISSUE TITLE
error in assets/css

### ISSUE THREAD

**Issue by nikhildutta333** [udacimak/udacimak#34]
I m really not sure why the error:enoent is occurring, so i was trying to download the nanodegree course and after the process was going smoothly for some time i suddenly got an error saying  no such file or directory, open 'Machine Learning Engineer Nanodegree v2.0.0/assets/css/fonts/data.json'

I don't know why there is a requirement for data.json in the in assets/css/fonts .to make sure there is something wrong I copied my half rendered to some other directory and rendered  a new one again I didn't notice any data,json generated inside this in the new render but I still got the same error after a while.

**Udacimak Log**
The following was present in the log file 

Uncaught Exception:
ERROR: write EIO
CODE: EIO
STACK: Error: write EIO
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
2019-04-28T18:54:56.475Z [[31merror[39m]: ERROR: ENOENT: no such file or directory, open 'Machine Learning Engineer Nanodegree v2.0.0/assets/css/fonts/data.json'
CODE: ENOENT
STACK: Error: ENOENT: no such file or directory, open 'Machine Learning Engineer Nanodegree v2.0.0/assets/css/fonts/data.json'
    at Object.openSync (fs.js:454:3)
    at Object.readFileSync (fs.js:354:35)
    at writeHtmlLesson (/home/nikhil/.nvm/versions/node/v12.0.0/lib/node_modules/udacimak/lib/commands/render/functions/writeHtmlLesson.js:38:26)
    at renderCourse (/home/nikhil/.nvm/versions/node/v12.0.0/lib/node_modules/udacimak/lib/commands/render/functions/renderCourse.js:115:45)
    at async render (/home/nikhil/.nvm/versions/node/v12.0.0/lib/node_modules/udacimak/lib/commands/render/index.js:20:5)

![Screenshot from 2019-04-29 01-22-56](https://user-images.githubusercontent.com/23122832/56869362-728dc400-6a1d-11e9-8a81-ed36ec9bce1a.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 15.04
 - Node version: (`node --v12.0.0')
 - npm version: (`npm --v6.9.0`)
 - Udacimak Version: (`v1.4.0`)
 - Browser [chrome]

**Course Information**
 - Nanodegree or Course name: machine learning engineer nanodegree v2.0.0 - Version: [e.g. v2.0.0]
 - Locale: [e.g. en-us]

**Comment by udacimak** [comment]
Please refer to this section of the `README`:
- https://github.com/udacimak/udacimak#important-render-directory-note
