### ISSUE TITLE
Render error: CODE: ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by sstihler** [udacimak/udacimak#37]
**Describe the bug**
I am using `udacimak 1.4.0` and getting the following error.

```shell
2019-05-17T14:49:15.955Z [error]: TYPEERROR [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
CODE: ERR_INVALID_ARG_TYPE
STACK: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.extname (path.js:830:5)
    at downloadMediaInHtml (C:\Users\sstih\AppData\Roaming\npm\node_modules\udacimak\lib\commands\utils\downloadMediaInHtml.js:66:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
**Desktop (please complete the following information):**
 - OS: Windows
 - Node version: `v10.15.3`
 - npm version: `6.4.1`
 - Udacimak Version: `v1.4.0`

**Course Information**
 - Nanodegree or Course name: Fundamentos Web Front-End nd-041
 - Version: v2.0.0
 - Locale: pt-br

**Comment by udacimak** [comment]
@sstihler 
Please provide the command that you wrote in the terminal that throws the error.
It looks like the error was due to an invalid command.

**Comment by sstihler** [comment]
The error is occurring at the time of rendering the course.
To download I have used: `udacimak download nd041`
There was no mistake.
To render I used: `udacimak render "Fundamentos Web Front-End v2.0.0"`
When it arrives in the folder 
`Fundamentos Web Front-End v2.0.0\Part 02-Module 01-Lesson 02_Lab - Sintaxe de HTML\08. Construindo links.html`
the error happens.
