### ISSUE TITLE
Unexpected Token error

### ISSUE THREAD

**Issue by syedtocode** [udacimak/udacimak#39]
Installed and ran the following which throws an runtime error saying unexpected token. Unable to execute any command as all of them resulted in the same error. 

>udacimak --version
/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/youtube-dl.js:52
  execFile(ytdlBinary, args, { ...execFileOpts, ...options }, function done(err, stdout, stderr) {
                               ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/udacimak/lib/commands/utils/downloadYoutube.js:18:41)

**Comment by udacimak** [comment]
Hi @syedtocode .

How did you install `udacimak`?

**Comment by syedtocode** [comment]
My sincere apologies as I somehow missed your email. I have installed udacimak as per your instruction on github. 

i.e. 

npm install -g udacimak

Many thanks for helping me.

**Comment by syedtocode** [comment]
I tried to install/update again but no luck as I see the same error repeating. 

Syeds-MBP-2:blog1 syedzulfiqar$ npm install -g udacimak
/usr/local/bin/udacimak -> /usr/local/lib/node_modules/udacimak/lib/index.js
/usr/local/lib
└─┬ udacimak@1.4.0 
  ├─┬ cheerio@1.0.0-rc.3
  │ └─┬ parse5@3.0.3
  │   └── @types/node@12.0.3 
  ├─┬ handlebars@4.1.2
  │ └── uglify-js@3.5.15 
  ├─┬ request@2.88.0
  │ └─┬ tough-cookie@2.4.3
  │   └── psl@1.1.32 
  └─┬ winston@3.2.1
    └── readable-stream@3.4.0 

Syeds-MBP-2:blog1 syedzulfiqar$ udacimak -version
/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/youtube-dl.js:52
  execFile(ytdlBinary, args, { ...execFileOpts, ...options }, function done(err, stdout, stderr) {
                               ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/udacimak/lib/commands/utils/downloadYoutube.js:18:41)

**Comment by sgmshaik** [comment]
your npm is probably out of date try updating that brag. use npm to install latest npm

**Comment by phommata** [comment]
I am running into this issue too still after updating to the latest npm. 
udacimak -v
/usr/local/lib/node_modules/udacimak/lib/index.js:31
_commander.default.command('download').description('Fetch course/Nanodegree data from Udacity and save them locally as JSON files.').arguments('[courseid...]').option('-t, --targetdir <targetdir>', 'Target directory to save downloaded course JSON data').action(async (courseids, options) => {
                                                                                                                                                                                                                                                                           ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

I have installed udacimak this way:
npm install -g udacimak

I am on npm version:
npm -v
6.14.4

Thanks in advance. Any help is appreciated.
