### ISSUE TITLE
Render stops on Deep Learning Foundation in Lab content

### ISSUE THREAD

**Issue by Heerozh** [udacimak/udacimak#4]
version 0.10.6,  windows 10

I tried it a few times and stopped here:

``` bash
2018-11-08T07:05:31.355Z [info]: Completed rendering lesson file D:\Udacity\Rendered/Deep Learning Foundation v1.0.0/Part 02-Module 04-Lesson 01_Cloud Computing/07. More Resources.html
2018-11-08T07:05:31.356Z [info]: ----------------------------------------
(node:10420) UnhandledPromiseRejectionWarning: TypeError: key_takeaways is not iterable
    at createHtmlLabIntroduction (C:\Users\x\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\lab\createHtmlLabIntroduction.js:37:24)
    at writeHtmlLab (C:\Users\x\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\writeHtmlLab.js:52:59)
    at async.eachSeries.error (C:\Users\x\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\writeHtmlLesson.js:79:108)
    at C:\Users\x\AppData\Roaming\npm\node_modules\udacimak\node_modules\async\dist\async.js:473:16
    at replenish (C:\Users\x\AppData\Roaming\npm\node_modules\udacimak\node_modules\async\dist\async.js:1006:25)
    at iterateeCallback (C:\Users\x\AppData\Roaming\npm\node_modules\udacimak\node_modules\async\dist\async.js:995:17)
    at C:\Users\x\AppData\Roaming\npm\node_modules\udacimak\node_modules\async\dist\async.js:969:16
    at then (C:\Users\x\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\writeHtmlConcept.js:110:7)
(node:10420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Thanks, this project helped me a lot. :)

**Comment by udacimak** [comment]
Thanks for reporting. I'm looking into this error. If possible, could you please send the json data to udacimak@tutanota.com? This error comes from the rendering of __Lab__ content, which is very new in Udacity and I'm not sure if I have enough information to make the Lab render stable.

**Comment by udacimak** [comment]
I have been able to fix the issue and have rendered the reported lesson without issues. Also found another bug occurred in a later lesson _due to `null` JSON data keys_ and have also fixed that.

I'll release an update soon and that will automatically close this issue. Once the next version is released, you can run `npm update -g udacimak` to update and run the render again.

Thanks again, @Heerozh for reporting!
