### ISSUE TITLE
 ERROR: status code 500

### ISSUE THREAD

**Issue by seanlee15** [udacimak/udacimak#40]
**Describe the bug**
Ran into error when rendering the course content. Should I be concerned about this situation, or just wait for a while. 

 npm version: 6.9.0
Udacimak: 1.4.0
MacOs 10.14 
Course to be downloaded: nt880 AI for trading

Error log 

✖ Getting Youtube video id CQ6QGAxbUF8 information
2019-05-22T21:01:08.541Z [error]: ERROR: status code 500
STACK: Error: status code 500
    at Request.response (/Users/sixuan/.nvm/versions/node/v12.3.0/lib/node_modules/udacimak/node_modules/youtube-dl/lib/youtube-dl.js:121:35)
    at Request.emit (events.js:200:13)
    at Request.onRequestResponse (/Users/sixuan/.nvm/versions/node/v12.3.0/lib/node_modules/udacimak/node_modules/request/request.js:1066:10)
    at ClientRequest.emit (events.js:200:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:573:23)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:460:22)
    at TLSSocket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)

**Comment by udacimak** [comment]
Could you try again? If it doesn't work, please send the JSON data to udacimak@tutanota.com , I can have a look. Thanks
