### ISSUE TITLE
ERROR: Unable to download webpage: <urlopen error [WinError 10060]

### ISSUE THREAD

**Issue by GitEasonXu** [udacimak/udacimak#41]
**Describe the bug**
`ERROR: Unable to download webpage: <urlopen error [WinError 10060]`,When I runned `udacimak render "Self-Driving Car Engineer v1.0.0"`

**To Reproduce**
1. Install udacimak is ok
2. Download json is ok
3. Using `udacimak render "Self-Driving Car Engineer v1.0.0` to render downloaded JSON 
5. _(Add more or edit as appropriate)_

**Udacimak Log**
Relevant portion of the logs from `udacimak.info.log`
and/or `udacimak.error.log` files:
```
2019-05-27T09:53:18.917Z [[31merror[39m]: ERROR: Command failed: C:\Users\Administrator\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin\youtube-dl.exe --dump-json --format=best --encoding utf8 http://www.youtube.com/watch?v=jHA__A61nqc
ERROR: Unable to download webpage: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。> (caused by URLError(TimeoutError(10060, '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。', None, 10060, None),))

CODE: 1
STACK: Error: Command failed: C:\Users\Administrator\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin\youtube-dl.exe --dump-json --format=best --encoding utf8 http://www.youtube.com/watch?v=jHA__A61nqc
ERROR: Unable to download webpage: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。> (caused by URLError(TimeoutError(10060, '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。', None, 10060, None),))

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2019-05-27T11:08:33.618Z [[31merror[39m]: ERROR: ENOENT: no such file or directory, open 'Self-Driving Car Engineer v1.0.0\assets\css\fonts\data.json'
CODE: ENOENT
STACK: Error: ENOENT: no such file or directory, open 'Self-Driving Car Engineer v1.0.0\assets\css\fonts\data.json'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at writeHtmlLesson (C:\Users\Administrator\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\writeHtmlLesson.js:38:26)
    at renderCourse (C:\Users\Administrator\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\renderCourse.js:115:45)
```

```shell
(base) PS>udacimak render "Self-Driving Car Engineer v1.0.0"
√ Download media file carnd.jpg
 ████████████████████████████████████████ 100% | ETA: 0s | 5609023/5609023
2019-05-27T09:49:45.523Z [info]: Downloaded media file carnd.jpg
2019-05-27T09:49:45.603Z [info]: Completed rendering Nanodegree summary file D:\Udacity\Self-Driving Car Engineer v1.0.0/index.html
2019-05-27T09:49:45.604Z [info]: ____________________

2019-05-27T09:49:45.642Z [info]: Completed rendering lesson summary file D:\Udacity\Self-Driving Car Engineer v1.0.0\Part 01-Module 01-Lesson 01_Welcome\index.html
2019-05-27T09:49:45.643Z [info]: ____________________

× Getting Youtube video id jHA__A61nqc information
2019-05-27T09:53:18.917Z [error]: ERROR: Command failed: C:\Users\Administrator\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin\youtube-dl.exe --dump-json --format=best --encoding utf8 http://www.youtube.com/watch?v=jHA__A61nqc
ERROR: Unable to download webpage: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。> (caused by URLError(TimeoutError(10060, '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。', None, 10060, None),))

CODE: 1
STACK: Error: Command failed: C:\Users\Administrator\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin\youtube-dl.exe --dump-json --format=best --encoding utf8 http://www.youtube.com/watch?v=jHA__A61nqc
ERROR: Unable to download webpage: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。> (caused by URLError(TimeoutError(10060, '由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。', None, 10060, None),))

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node version: v10.15.3
 - npm version: 6.4.1
 - Udacimak Version: v1.4.0
 - Browser chrome

**Course Information**
 - Nanodegree or Course name: Self-Driving Car Engineer Nanodegree
 - Version: v1.0.0
 - Locale: en-us

**Additional context**
I can access video, if I enter `https://www.youtube.com/watch?v=jHA__A61nqc` by chrome.

**Comment by udacimak** [comment]
@GitEasonXu Could you try it over a VPN?
You can also email me the JSON data to udacimak@tutanota.com , see if I face the same issue on my end.

**Comment by GitEasonXu** [comment]
@udacimak I have sent `data.json` to your email. Yes, I have used VPN.
Thank you!

**Comment by GitEasonXu** [comment]
I retry again today, but get such error:
```
(base) PS>udacimak render "Self-Driving Car Engineer v1.0.0" --targetdir "Self_Driving_Car"
2019-05-28T03:50:38.813Z [info]: Image already exists. Skip downloading Self_Driving_Car\Self-Driving Car Engineer v1.0.0\img\carnd.jpg
2019-05-28T03:50:38.842Z [info]: Completed rendering Nanodegree summary file Self_Driving_Car\Self-Driving Car Engineer v1.0.0/index.html
2019-05-28T03:50:38.844Z [info]: ____________________

2019-05-28T03:50:38.865Z [info]: Completed rendering lesson summary file Self_Driving_Car\Self-Driving Car Engineer v1.0.0\Part 01-Module 01-Lesson 01_Welcome\index.html
2019-05-28T03:50:38.867Z [info]: ____________________

× Getting Youtube video id jHA__A61nqc information
2019-05-28T03:51:05.777Z [error]: ERROR: connect ETIMEDOUT 67.228.37.26:443
CODE: ETIMEDOUT
STACK: Error: connect ETIMEDOUT 67.228.37.26:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
```

**Comment by udacimak** [comment]
@GitEasonXu I'm able to render your JSON data.

I'm pretty sure that it must be some issue with the internet connection. Could you try on a different network?

**Comment by GitEasonXu** [comment]
@udacimak
Thank you so much for your reply.  I will try again according to your advice.
Thanks!
