### ISSUE TITLE
ERROR: Error: read ECONNRESET

### ISSUE THREAD

**Issue by brijeshkamani11** [udacimak/udacimak#44]
I just install this software and follow your steps..
but i cannnot download due to this error...
```
C:\Users\bk>udacimak download ud1028
2019-06-12T11:53:11.436Z [info]: Downloaded lesson JSON for C:\Users\bk\Passwordless Login Solutions for iOS v1.0.0\Lesson 01_Introduction to Passwordless Login Solutions
2019-06-12T11:53:15.345Z [info]: Downloaded lesson JSON for C:\Users\bk\Passwordless Login Solutions for iOS v1.0.0\Lesson 02_Account Kit
2019-06-12T11:54:25.213Z [error]: Failed to download course. See error below:
ERROR: Error: read ECONNRESET
STACK: Error: Error: read ECONNRESET
    at Request._callback (C:\Users\bk\AppData\Roaming\npm\node_modules\udacimak\lib\api\fetchApiUdacityGraphql.js:51:16)
    at self.callback (C:\Users\bk\AppData\Roaming\npm\node_modules\udacimak\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (C:\Users\bk\AppData\Roaming\npm\node_modules\udacimak\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
so anyone has solution of this error?

**Comment by udacimak** [comment]
@brijeshkamani11 Must be something with the internet. Have you tried on a different internet connection?

**Comment by brijeshkamani11** [comment]
Yes my Internet connection is good and i also try from different network
still its not work...

**Comment by udacimak** [comment]
Do you see the same error message when trying from a different network?

**Comment by udacimak** [comment]
Note that I can download it on my end, so I guess it must be some sort of network issue. Let me know.

**Comment by brijeshkamani11** [comment]
Yah, you right its solved on different network. May be problem is in my
network now I'm able to download jason data thank you so much for your help.
but render step is still remaining. if any problem occurs on that step I'll
defiantly ask for your help...but for now thanks for your help.....
