### ISSUE TITLE
SyntaxError: Non-UTF-8 code starting with '\x97'

### ISSUE THREAD

**Issue by AnkS4** [udacimak/udacimak#47]
**Describe the bug**
Render failure on specific course/video.

**To Reproduce**
1. udacimak download ud187
2. udacimak render "Tensorflow free course v1.0.0"

**Udacimak Log**
Relevant portion of the logs from `udacimak.info.log`
and/or `udacimak.error.log` files:
https://gist.github.com/AnkS4/921c9c69de226055ac8198629168fe3e

```shell
udacimak render "Tensorflow free course v1.0.0"
2019-07-01T06:58:03.869Z [info]: Completed rendering lesson summary file /home/anks/udacimak/Tensorflow free course v1.0.1/Lesson 01_Welcome to the Course/index.html
2019-07-01T06:58:03.884Z [info]: ____________________

✖ Getting Youtube video id sf-YAUHf-IY information
2019-07-01T06:58:04.143Z [error]: ERROR: Command failed: /home/anks/.npm-global/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl --dump-json --format=best http://www.youtube.com/watch?v=sf-YAUHf-IY
  File "/home/anks/.npm-global/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl", line 2
SyntaxError: Non-UTF-8 code starting with '\x97' in file /home/anks/.npm-global/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

CODE: 1
STACK: Error: Command failed: /home/anks/.npm-global/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl --dump-json --format=best http://www.youtube.com/watch?v=sf-YAUHf-IY
  File "/home/anks/.npm-global/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl", line 2
SyntaxError: Non-UTF-8 code starting with '\x97' in file /home/anks/.npm-global/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

    at ChildProcess.exithandler (child_process.js:299:12)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)

```

**Desktop (please complete the following information):**
 - OS: Manjaro LInux
 - Node version: v11.15.0
 - npm version: 6.9.0
 - Udacimak Version: v1.4.0

**Course Information**
 - Nanodegree or Course name: [Intro To Tensorflow] (ud187)
 - Version: [e.g. v1.0.0]
 - Locale: [e.g. en-us]

**Comment by udacimak** [comment]
@AnkS4 I was able to download and render the course on my Windows and MacOS machine without issues.
It looks like an issue with `youtube-dl` package. 
Could you try on a different machine?

**Comment by AnkS4** [comment]
Working with updated packages.
