### ISSUE TITLE
Unexpected token T in JSON at position 0

### ISSUE THREAD

**Issue by brichase** [udacimak/udacimak#48]
**Describe the bug**
I've used the tool to download 2 other nanodegrees. Thanks! 

Downloading nd002, it downloads a large portion of the json files but errors out at one point.

**Error note**
2019-07-21T22:15:07.178Z [^[[31merror^[[39m]: Uncaught Exception:
SYNTAXERROR: Unexpected token T in JSON at position 0
STACK: SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/Users/brianchase/.nvm/versions/node/v12.6.0/lib/node_modules/udacimak/lib/api/fetchApiUdacityGraphql.js:53:30)
    at Request.self.callback (/Users/brianchase/.nvm/versions/node/v12.6.0/lib/node_modules/udacimak/node_modules/request/request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.<anonymous> (/Users/brianchase/.nvm/versions/node/v12.6.0/lib/node_modules/udacimak/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:203:13)
    at IncomingMessage.<anonymous> (/Users/brianchase/.nvm/versions/node/v12.6.0/lib/node_modules/udacimak/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:291:20)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1154:12)

**Where the info log stops**
2019-07-21T22:15:06.943Z [^[[32minfo^[[39m]: Downloaded lesson JSON for /Volumes/Lexar/Udacity/data_analyst/json2/Data Analyst Nanodegree v1.0.0/Part 17_Practical Statistics/Module 01_Sebastian Stats/Lesson 05_Binomial Distribution
2019-07-21T22:15:07.070Z [^[[32minfo^[[39m]: Downloaded lesson JSON for /Volumes/Lexar/Udacity/data_analyst/json2/Data Analyst Nanodegree v1.0.0/Part 17_Practical Statistics/Module 01_Sebastian Stats/Lesson 06_Conditional Probability
2019-07-21T22:15:07.178Z [^[[31merror^[[39m]: Uncaught Exception:
SYNTAXERROR: Unexpected token T in JSON at position 0

**Udacimak Log**
2019-07-21T22:15:06.943Z [^[[32minfo^[[39m]: Downloaded lesson JSON for /Volumes/Lexar/Udacity/data_analyst/json2/Data Analyst Nanodegree v1.0.0/Part 17_Practical Statistics/Module 01_Sebastian Stats/Lesson 05_Binomial Distribution
2019-07-21T22:15:07.070Z [^[[32minfo^[[39m]: Downloaded lesson JSON for /Volumes/Lexar/Udacity/data_analyst/json2/Data Analyst Nanodegree v1.0.0/Part 17_Practical Statistics/Module 01_Sebastian Stats/Lesson 06_Conditional Probability
2019-07-21T22:15:07.178Z [^[[31merror^[[39m]: Uncaught Exception:
SYNTAXERROR: Unexpected token T in JSON at position 0

```shell
udacimak download nd002
```

**Desktop (please complete the following information):**
 - OS: MacOS mojave 10.14.05
 - Node version: (`node --version`) v12.6.0
 - npm version: (`npm --version`) 6.9.0
 - Udacimak Version: (`udacimak --version`) v1.4.2
 - Browser [e.g. chrome, safari] Chrome

**Course Information**
 - Nanodegree or Course name: Data Analyst Nanodegree
 - Version: [e.g. v1.0.0] v1.0.0
 - Locale: [e.g. en-us] en-us

**Comment by udacimak** [comment]
Do you have full access to the Nanodegree?

I can't replicate the issue because I can download successfully on my computer. It's also hard to debug the `download` command because it requires access token.

Please try again and let me know, I'll see what I can do

**Comment by brichase** [comment]
I do have full access to the Nanodegree. The next file it should be downloading is the section on Bayes rule --- and I can access that. 

I've tried again with the same result. Any suggestions where to look to debug? Maybe I can be of help.

**Comment by udacimak** [comment]
@brichase It'd be great if you could debug the source code, though it requires familiarity with Node JS.

It's quite hard to debug on my end because it's working fine for me. For now, could you try downloading on another machine to see if it works?

**Comment by brichase** [comment]
Updated udacimak and ran it again on the same machine---and it now works. Not sure if it had to do with the program or the website.
