### ISSUE TITLE
Failed to find nanodegree

### ISSUE THREAD

**Issue by MakVihas** [udacimak/udacimak#56]

**Comment by MakVihas** [comment]
2019-10-10T14:15:40.923Z [info]: Start downloading Nanodegree nd001 from Udacity API
✖ Get Nanodegree nd001 information
✖ Get Nanodegree nd001 information
2019-10-10T14:15:42.344Z [error]: Failed to download course. See error below:
ERROR: Fail to find Nanodegree key nd001 in your profile. The key nd001 either doesn't exist or you don't have access to it.
STACK: Error: Fail to find Nanodegree key nd001 in your profile. The key nd001 either doesn't exist or you don't have access to it.
    at downloadNanodegree (/home/atoz/.npm-global/lib/node_modules/udacimak/lib/commands/download/functions/downloadNanodegree.js:43:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by udacimak** [comment]
@MakVihas 

Do you have subscription for `nd001`?

Also, can you run `udacimak listnd` to see what NDs you have access to and if `nd001` is listed?
