### ISSUE TITLE
Error while rendering the SDND program

### ISSUE THREAD

**Issue by gpokhark** [udacimak/udacimak#57]
I am using Ubuntu OS and while rendering the SDND program I am getting following error -

<pre>ERROR: EIO: i/o error, scandir &apos;Udacity_Rendered_Courses/Self-Driving Car Engineer v2.0.0/Part 01-Module 05-Lesson 03_C++ Checkpoint&apos;
CODE: EIO
STACK: Error: EIO: i/o error, scandir &apos;Udacity_Rendered_Courses/Self-Driving Car Engineer v2.0.0/Part 01-Module 05-Lesson 03_C++ Checkpoint&apos;
    at Object.fs.readdirSync (fs.js:904:18)
    at safeReadDirSync (/usr/local/lib/node_modules/udacimak/node_modules/directory-tree/lib/directory-tree.js:13:16)
    at directoryTree (/usr/local/lib/node_modules/udacimak/node_modules/directory-tree/lib/directory-tree.js:91:17)
    at deleteFilesInFolder (/usr/local/lib/node_modules/udacimak/lib/commands/utils/deleteFilesInFolder.js:21:41)
    at writeHtmlLesson (/usr/local/lib/node_modules/udacimak/lib/commands/render/functions/writeHtmlLesson.js:36:34)
    at renderCourse (/usr/local/lib/node_modules/udacimak/lib/commands/render/functions/renderCourse.js:115:45)
    at &lt;anonymous&gt;
</pre>

**Comment by udacimak** [comment]
@gpokhark 

Please email me the JSON files of the ND to udacimak@tutanota.com so I can have a look.

**Comment by gpokhark** [comment]
Oh thank you I downloaded the JSON files again and then it worked, something was wrong with the original JSON files,
