### ISSUE TITLE
Unhandled Promise Rejection Error

### ISSUE THREAD

**Issue by Hanson7300** [udacimak/udacimak#59]
**Describe the bug**
Unhandled Promise Rejection:ERROR: spawn UNKNOWN
**Udacimak Log**

```shell
udacimak render C:\Users\Hanson\Android -t C:\Users\Hanson\Desktop
2019-10-24T07:35:12.289Z [info]: Image already exists. Skip downloading C:\Users\Hanson\Desktop\Android\img\android-basics-large.jpg
2019-10-24T07:35:12.313Z [info]: Completed rendering Nanodegree summary file C:\Users\Hanson\Desktop\Android/index.html
2019-10-24T07:35:12.314Z [info]: ____________________

2019-10-24T07:35:12.337Z [info]: Completed rendering lesson summary file C:\Users\Hanson\Desktop\Android\Part 01-Module 01-Lesson 01_课程1A：打造布局\index.html
2019-10-24T07:35:12.338Z [info]: ____________________

- Getting Youtube video id zO9Bu0IwFTM information2019-10-24T07:35:12.358Z [error]: Unhandled Promise Rejection:ERROR: spawn UNKNOWN
CODE: UNKNOWN
STACK: Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:551:9)
    at execFile (child_process.js:221:15)
    at youtubeDl (C:\Users\Hanson\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\youtube-dl.js:25:3)
    at call (C:\Users\Hanson\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\youtube-dl.js:153:10)
    at Function.getInfo (C:\Users\Hanson\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\youtube-dl.js:238:3)
    at module.exports (C:\Users\Hanson\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\youtube-dl.js:100:8)
    at Promise (C:\Users\Hanson\AppData\Roaming\npm\node_modules\udacimak\lib\commands\utils\downloadYoutube.js:89:42)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
**Desktop (please complete the following information):**
 - OS: [Windows 10 1903 ]
 - Node version: (`10.16.3`)
 - npm version: (`6.12.0`)
 - Udacimak Version: (`1.4.5`)
 - Browser [chrome]

**Course Information**
 - Nanodegree or Course name: [Android Basic Nanodegree]
 - Version: [v1.0.0]
 - Locale: [zh-cn]

**Additional context**
I can watch the youtube video via the id zO9Bu0IwFTM , not sure where goes wrong :)

**Comment by udacimak** [comment]
@Hanson7300 The error is thrown by `youtube-dl`.

Could you try rendering in a different VPN network?

**Comment by Hanson7300** [comment]
![image](https://user-images.githubusercontent.com/22568493/67538793-bafb1580-f712-11e9-916f-9cbd26f1698d.png)
@udacimak I tried ShadowsocksR and V2ray, both works when downloading youtube videos. 
Render still doesn't work.

**Comment by udacimak** [comment]
@Hanson7300 that's weird. Actually it's an error from `youtube-dl` so I'm afraid I can't provide much help. It's working on my end so I have to assume that the CLI is working fine.

Are you able to try on another network?

**Comment by Hanson7300** [comment]
@udacimak I re-install node.js,npm,udacimak, and got the error unable to locate `youtube-dl`.I tried to put youtube-dl.exe into the path but doesn't work...
![23](https://user-images.githubusercontent.com/22568493/67780477-1aee1500-faa1-11e9-909b-dba5a1630b5c.png)
Error: ERROR: unable to locate `youtube-dl` at C:\Users\Hanson\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin
    at module.exports (C:\Users\Hanson\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\get-binary.js:11:11)
    at Object.<anonymous> (C:\Users\Hanson\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\youtube-dl.js:18:41)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Hanson\AppData\Roaming\npm\node_modules\udacimak\lib\commands\utils\downloadYoutube.js:18:41)
    at Module._compile (internal/modules/cjs/loader.js:971:30)

**Comment by udacimak** [comment]
@Hanson7300 
`youtube-dl` can't be run directly as such. It is installed and used internally by `udacimak`

**Comment by vsay01** [comment]
I have the same issue @Hanson7300 

/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/get-binary.js:11
    throw new Error('ERROR: unable to locate `youtube-dl` at ' + binPath)
    ^

Error: ERROR: unable to locate `youtube-dl` at /usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/bin
    at module.exports (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/get-binary.js:11:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/youtube-dl.js:18:41)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/udacimak/lib/commands/utils/downloadYoutube.js:18:41)

**Comment by vsay01** [comment]
@Hanson7300 

@udacimak suggest me to use udacimak docker version, and it's working, so you can try that out.

**Comment by rupeshvins** [comment]
@vsay01 
Hi
By Docker version r u able to download full course and how to use udacimak renderdir command

**Comment by rupeshvins** [comment]
@vsay01 
Hi
Plz check https://github.com/udacimak/udacimak/issues/67
I download and install docker toolbox but show some error, can u suggest me what can I do.
Thanks

**Comment by rupeshvins** [comment]
@vsay01 
Hi
Ur udacimak Docker version is working so can u download [Intro to Deep Learning with PyTorch](https://classroom.udacity.com/courses/ud188) and share with via google drive.
Thanks

**Comment by Hanson7300** [comment]
@vsay01 I tried many ways to apply my VPN network on docker container, but all failed.

**Comment by vsay01** [comment]
@Hanson7300 Could you share the log you have ?

**Comment by rupeshvins** [comment]
Udacimak not working, plz try other methods.
Even I try all Udacimak method and Dockers but no result
