### ISSUE TITLE
Can't download !

### ISSUE THREAD

**Issue by akashbisht81** [udacimak/udacimak#63]
C:\Users\Akash>udacimak render C:\Users\Akash\Machine Learning - Introduction v2.0.0
2019-11-16T19:01:23.009Z [error]: ERROR: Path to downloaded Udacity course/Nanodegree doesn't exist.
STACK: Error: Path to downloaded Udacity course/Nanodegree doesn't exist.
    at renderCourse (C:\Users\Akash\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\renderCourse.js:43:11)
    at async render (C:\Users\Akash\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\index.js:20:5)

**Comment by udacimak** [comment]
@akashbisht81 You need to put the path in double-quotes because it contains space character

**Comment by akashbisht81** [comment]
Gotcha !, I just re-named the file name without spaces and replaced that
name instead, and now it worked like a charm. Thanks.

**Comment by akashbisht81** [comment]
@udacimak I have downloaded the content for personal-use, But i have one issue, the video is not in HD, how can i download all the contents in HD format. Any suggestions on that ?

**Comment by udacimak** [comment]
@akashbisht81 I've tried this before but it's not possible yet - audio is lost when downloading HD video.

**Comment by akashbisht81** [comment]
Okay.
