### ISSUE TITLE
not able to download the content

### ISSUE THREAD

**Issue by shubham-ai** [udacimak/udacimak#64]
Failed to download course. See error below:
TYPEERROR: Cannot destructure property 'lessons' of 'course' as it is null.
STACK: TypeError: Cannot destructure property 'lessons' of 'course' as it is null.
    at downloadCourse (/usr/local/lib/node_modules/udacimak/lib/commands/download/functions/downloadCourse.js:33:7)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async download (/usr/local/lib/node_modules/udacimak/lib/commands/download/index.js:39:9)

**Comment by udacimak** [comment]
Please provide full detail and commands that you run to help me replicate
