### ISSUE TITLE
Cannot render the project once fully downloaded

### ISSUE THREAD

**Issue by PulkitBanta** [udacimak/udacimak#71]
**Describe the bug**
The webpage after downloading the whole project do not render again as it says that it cannot find the data.json file to render the project, however opening the webpage from index.html do not looks even like the original webpage, It just seems to be a webpage without any CSS and styling.

**To Reproduce**
1. Download the course (ud894).
2. Try to render it.

**Expected behavior**
After downloading the whole course I expected it to render to the default webpage and open just like the original webpage should open.

**Udacimak Log**
Relevant portion of the logs from `udacimak.info.log`
and/or `udacimak.error.log` files:
[udacimak.error.log](https://github.com/udacimak/udacimak/files/3984887/udacimak.error.log)

```shell
D:\Study>udacimak render "Front End Frameworks v1.0.0"
2019-12-19T17:13:17.949Z [error]: ERROR: ENOENT: no such file or directory, open 'Front End Frameworks v1.0.0\assets\data.json'
CODE: ENOENT
STACK: Error: ENOENT: no such file or directory, open 'Front End Frameworks v1.0.0\assets\data.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at writeHtmlLesson (C:\Users\pulki\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\writeHtmlLesson.js:38:26)
    at renderCourse (C:\Users\pulki\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\renderCourse.js:93:37)
```
```shell
D:\Study>udacimak render "Front End Frameworks v1.0.0" --targetdir renderProject
2019-12-19T17:40:20.731Z [error]: ERROR: ENOENT: no such file or directory, open 'Front End Frameworks v1.0.0\assets\data.json'
CODE: ENOENT
STACK: Error: ENOENT: no such file or directory, open 'Front End Frameworks v1.0.0\assets\data.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at writeHtmlLesson (C:\Users\pulki\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\writeHtmlLesson.js:38:26)
    at renderCourse (C:\Users\pulki\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\renderCourse.js:93:37)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/43134750/71194226-90ac7b00-22b1-11ea-8400-8c98ab464039.png)

**Original Webpage**
![image](https://user-images.githubusercontent.com/43134750/71194301-b3d72a80-22b1-11ea-8061-b9649801edc4.png)

**My webpage after opening it from local files at index.html**
![image](https://user-images.githubusercontent.com/43134750/71194360-cb161800-22b1-11ea-99c2-849d8fddc83e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Node version: v10.16.3
 - npm version: v6.13.4
 - Udacimak Version: v1.4.5
 - Browser : Firefox

**Course Information**
 - Front End Frameworks v1.0.0 (ud894)
 - Version: v1.0.0
 - Locale: en-India

**Comment by udacimak** [comment]
@PulkitBanta 
Udacimak doesn't aim to make the webpage to look exactly the same as Udacity website.

For the `render` issue, please see this README section:

- https://github.com/udacimak/udacimak/wiki/How-to-Use#important-render-directory-note

You must separate render folder from download folder.

**Comment by PulkitBanta** [comment]
After downloading the course once I tried to render it to target directory but same error occurred.
```shell
D:\Study>udacimak render "Front End Frameworks v1.0.0" --targetdir renderProject
2019-12-19T17:40:20.731Z [error]: ERROR: ENOENT: no such file or directory, open 'Front End Frameworks v1.0.0\assets\data.json'
CODE: ENOENT
STACK: Error: ENOENT: no such file or directory, open 'Front End Frameworks v1.0.0\assets\data.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at writeHtmlLesson (C:\Users\pulki\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\writeHtmlLesson.js:38:26)
    at renderCourse (C:\Users\pulki\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\renderCourse.js:93:37)
```

**Comment by udacimak** [comment]
The `Front End Frameworks v1.0.0` folder contains `assets` folder, which means you must have rendered into that folder before.

Please make sure the source folder for `render` is the download folder (the one that contains only `.json` files. The target render folder must be different from the source.

**Comment by PulkitBanta** [comment]
Thanks, for your help.
