### ISSUE TITLE
ERROR: 9PoZXr8dxFA: YouTube said: Unable to extract video data

### ISSUE THREAD

**Issue by saeedarabi92** [udacimak/udacimak#77]
**Describe the bug**

When I want to render the files I received this error:

```
root@523e94fd96be:/# udacimak render Robotics\ Software\ Engineer\ v2.0.0/ --targetdir downloads
2020-02-05T17:59:50.910Z [info]: Image already exists. Skip downloading downloads/Robotics Software Engineer v2.0.0/img/nd209-robond-hero.png
2020-02-05T17:59:50.933Z [info]: Completed rendering Nanodegree summary file downloads/Robotics Software Engineer v2.0.0/index.html
2020-02-05T17:59:50.933Z [info]: ____________________

2020-02-05T17:59:50.955Z [info]: Completed rendering lesson summary file downloads/Robotics Software Engineer v2.0.0/Part 01-Module 01-Lesson 01_Welcome/index.html
2020-02-05T17:59:50.955Z [info]: ____________________

✖ Getting Youtube video id 9PoZXr8dxFA information
2020-02-05T17:59:52.691Z [error]: ERROR: Command failed: /usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl --dump-json --format=best http://www.youtube.com/watch?v=9PoZXr8dxFA
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: 9PoZXr8dxFA: YouTube said: Unable to extract video data

CODE: 1
STACK: Error: Command failed: /usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl --dump-json --format=best http://www.youtube.com/watch?v=9PoZXr8dxFA
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: 9PoZXr8dxFA: YouTube said: Unable to extract video data

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:257:5)

```

**To Reproduce**
I ran this command in docker:
`udacimak render Robotics\ Software\ Engineer\ v2.0.0/ --targetdir downloads`

**Expected behavior**

**Udacimak Log**
Relevant portion of the logs from `udacimak.info.log`
and/or `udacimak.error.log` files:

```shell
root@8e4d378579f1:/# cat udacimak.error.log 
2020-02-05T18:24:42.134Z [error]: ERROR: Command failed: /usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl --dump-json --format=best http://www.youtube.com/watch?v=9PoZXr8dxFA
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: 9PoZXr8dxFA: YouTube said: Unable to extract video data

CODE: 1
STACK: Error: Command failed: /usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl --dump-json --format=best http://www.youtube.com/watch?v=9PoZXr8dxFA
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: 9PoZXr8dxFA: YouTube said: Unable to extract video data

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:387:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:611:12)
```

```
root@8e4d378579f1:/# cat udacimak.info.log 
2020-02-05T18:23:13.732Z [warn]: Udacity authentication token hasn't been set.
2020-02-05T18:23:17.440Z [info]: Hi Saeed. You have successfully saved authentication token locally!
2020-02-05T18:23:17.954Z [info]: Hi Saeed!
2020-02-05T18:23:17.954Z [info]: 
2020-02-05T18:23:17.955Z [info]: Here's a list of your graduated Nanodegrees (list by Nanodegree key only. The API doesn't return Nanodegree name so it can't be listed here):
2020-02-05T18:23:17.955Z [info]:  - nd209 version 2.0.0 (locale: en-us)
2020-02-05T18:23:17.956Z [info]: 
2020-02-05T18:23:17.956Z [info]: Here's a list of your enrolled Nanodegrees:
2020-02-05T18:23:17.956Z [info]:  - nd027 version 1.0.0 (locale: en-us): Data Engineering Nanodegree
2020-02-05T18:23:17.957Z [info]:  - nd013 version 1.0.0 (locale: en-us): Self-Driving Car Engineer
2020-02-05T18:23:52.206Z [info]: Start downloading Nanodegree nd209 from Udacity API
2020-02-05T18:23:53.149Z [info]: You're authorized to download version 2.0.0, locale en-us of Nanodegree nd209
2020-02-05T18:23:53.742Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 01_Introduction to Robotics/Module 01_Introduction to Robotics/Lesson 01_Welcome
2020-02-05T18:23:54.449Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 01_Introduction to Robotics/Module 01_Introduction to Robotics/Lesson 02_What is a Robot
2020-02-05T18:23:54.757Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 01_Introduction to Robotics/Module 01_Introduction to Robotics/Lesson 03_Career Support Overview
2020-02-05T18:23:55.050Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 01_Introduction to Robotics/Module 01_Introduction to Robotics/Lesson 04_Welcome to Udacity
2020-02-05T18:23:55.300Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 01_Introduction to Robotics/Module 01_Introduction to Robotics/Lesson 05_Get Help with Your Account
2020-02-05T18:23:55.568Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 01_Introduction to Robotics/Module 01_Introduction to Robotics/Lesson 06_Getting Started
2020-02-05T18:23:55.843Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 02_Gazebo World/Module 01_Gazebo World/Lesson 01_Gazebo Basics
2020-02-05T18:23:56.132Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 02_Gazebo World/Module 01_Gazebo World/Lesson 02_Project Build My World
2020-02-05T18:23:56.461Z [info]: Downloaded rubric JSON of project Build My World for /Robotics Software Engineer v2.0.0/Part 02_Gazebo World/Module 01_Gazebo World/Lesson 02_Project Build My World
2020-02-05T18:23:56.756Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 03_ROS Essentials/Module 01_ROS Essentials/Lesson 01_Introduction to ROS
2020-02-05T18:23:57.021Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 03_ROS Essentials/Module 01_ROS Essentials/Lesson 02_Packages & Catkin Workspaces
2020-02-05T18:23:57.345Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 03_ROS Essentials/Module 01_ROS Essentials/Lesson 03_Write ROS Nodes
2020-02-05T18:23:57.608Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 03_ROS Essentials/Module 01_ROS Essentials/Lesson 04_Project Go Chase It!
2020-02-05T18:23:57.922Z [info]: Downloaded rubric JSON of project Go Chase It! for /Robotics Software Engineer v2.0.0/Part 03_ROS Essentials/Module 01_ROS Essentials/Lesson 04_Project Go Chase It!
2020-02-05T18:23:58.202Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 03_ROS Essentials/Module 01_ROS Essentials/Lesson 05_Optimize Your GitHub Profile
2020-02-05T18:23:59.173Z [info]: Downloaded rubric JSON of project Optimize Your GitHub Profile for /Robotics Software Engineer v2.0.0/Part 03_ROS Essentials/Module 01_ROS Essentials/Lesson 05_Optimize Your GitHub Profile
2020-02-05T18:23:59.446Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 04_Localization/Module 01_Localization/Lesson 01_Introduction to Localization
2020-02-05T18:24:00.260Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 04_Localization/Module 01_Localization/Lesson 02_Kalman Filters
2020-02-05T18:24:00.535Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 04_Localization/Module 01_Localization/Lesson 03_Lab Kalman Filters
2020-02-05T18:24:01.106Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 04_Localization/Module 01_Localization/Lesson 04_Monte Carlo Localization
2020-02-05T18:24:01.877Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 04_Localization/Module 01_Localization/Lesson 05_Build MCL in C++
2020-02-05T18:24:02.194Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 04_Localization/Module 01_Localization/Lesson 06_Where Am I
2020-02-05T18:24:02.480Z [info]: Downloaded rubric JSON of project Where Am I for /Robotics Software Engineer v2.0.0/Part 04_Localization/Module 01_Localization/Lesson 06_Where Am I
2020-02-05T18:24:02.731Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 05_Mapping and SLAM/Module 01_Mapping and SLAM/Lesson 01_Introduction to Mapping and SLAM
2020-02-05T18:24:03.740Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 05_Mapping and SLAM/Module 01_Mapping and SLAM/Lesson 02_ Occupancy Grid Mapping
2020-02-05T18:24:04.380Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 05_Mapping and SLAM/Module 01_Mapping and SLAM/Lesson 03_Grid-based FastSLAM
2020-02-05T18:24:04.732Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 05_Mapping and SLAM/Module 01_Mapping and SLAM/Lesson 04_GraphSLAM
2020-02-05T18:24:05.041Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 05_Mapping and SLAM/Module 01_Mapping and SLAM/Lesson 05_Map My World
2020-02-05T18:24:05.312Z [info]: Downloaded rubric JSON of project Map My World for /Robotics Software Engineer v2.0.0/Part 05_Mapping and SLAM/Module 01_Mapping and SLAM/Lesson 05_Map My World
2020-02-05T18:24:05.584Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 05_Mapping and SLAM/Module 01_Mapping and SLAM/Lesson 06_Take 30 Min to Improve your LinkedIn
2020-02-05T18:24:06.350Z [info]: Downloaded rubric JSON of project Improve Your LinkedIn Profile for /Robotics Software Engineer v2.0.0/Part 05_Mapping and SLAM/Module 01_Mapping and SLAM/Lesson 06_Take 30 Min to Improve your LinkedIn
2020-02-05T18:24:06.680Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 06_Path Planning and Navigation/Module 01_Path Planning and Navigation/Lesson 01_Intro to Path Planning and Navigation
2020-02-05T18:24:07.381Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 06_Path Planning and Navigation/Module 01_Path Planning and Navigation/Lesson 02_Classic Path Planning
2020-02-05T18:24:08.115Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 06_Path Planning and Navigation/Module 01_Path Planning and Navigation/Lesson 03_Lab Path Planning
2020-02-05T18:24:08.376Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 06_Path Planning and Navigation/Module 01_Path Planning and Navigation/Lesson 04_Sample-Based and Probabilistic Path Planning
2020-02-05T18:24:08.676Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 06_Path Planning and Navigation/Module 01_Path Planning and Navigation/Lesson 05_Home Service Robot
2020-02-05T18:24:08.957Z [info]: Downloaded rubric JSON of project Home Service Robot for /Robotics Software Engineer v2.0.0/Part 06_Path Planning and Navigation/Module 01_Path Planning and Navigation/Lesson 05_Home Service Robot
2020-02-05T18:24:09.217Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 07_Optional KUKA Path Planning Project/Module 01_Optional Kuka Path Planning Project/Lesson 01_Project Introduction
2020-02-05T18:24:09.499Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 07_Optional KUKA Path Planning Project/Module 01_Optional Kuka Path Planning Project/Lesson 02_Project Details
2020-02-05T18:24:09.823Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 08_Autonomous Systems Interview/Module 01_Autonomous Systems Interview/Lesson 01_Autonomous Systems Interview Practice
2020-02-05T18:24:10.126Z [info]: Downloaded rubric JSON of project Autonomous Systems Interview Practice Project for /Robotics Software Engineer v2.0.0/Part 08_Autonomous Systems Interview/Module 01_Autonomous Systems Interview/Lesson 01_Autonomous Systems Interview Practice
2020-02-05T18:24:10.549Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 09_Free Preview/Module 01_Free Preview Lessons/Lesson 01_Gazebo Basics
2020-02-05T18:24:10.919Z [info]: Downloaded lesson JSON for /Robotics Software Engineer v2.0.0/Part 09_Free Preview/Module 01_Free Preview Lessons/Lesson 02_Introduction to ROS
2020-02-05T18:24:10.919Z [info]: Completed downloading Robotics Software Engineer Nanodegree's JSON data from Udacity API
2020-02-05T18:24:10.919Z [info]: ____________________

2020-02-05T18:24:38.963Z [info]: Image already exists. Skip downloading downloads/Robotics Software Engineer v2.0.0/img/nd209-robond-hero.png
2020-02-05T18:24:38.994Z [info]: Completed rendering Nanodegree summary file downloads/Robotics Software Engineer v2.0.0/index.html
2020-02-05T18:24:38.994Z [info]: ____________________

2020-02-05T18:24:39.118Z [info]: Completed rendering lesson summary file downloads/Robotics Software Engineer v2.0.0/Part 01-Module 01-Lesson 01_Welcome/index.html
2020-02-05T18:24:39.118Z [info]: ____________________

2020-02-05T18:24:42.134Z [error]: ERROR: Command failed: /usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl --dump-json --format=best http://www.youtube.com/watch?v=9PoZXr8dxFA
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: 9PoZXr8dxFA: YouTube said: Unable to extract video data

CODE: 1
STACK: Error: Command failed: /usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl --dump-json --format=best http://www.youtube.com/watch?v=9PoZXr8dxFA
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: 9PoZXr8dxFA: YouTube said: Unable to extract video data

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:387:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:611:12)
root@8e4d378579f1:/# 

```
**Desktop (please complete the following information):**
 - OS: Ubuntu 16
 - Node version: v4.2.6
 - npm version: 3.5.2
 - Udacimak Version: udacimak: command not found (I used docker)
 - Browser: chrome

**Course Information**
 - Nanodegree or Course name: Robotics Engineering Nanodegree (graduated)
 - Version: v2.0.0
 - Locale: en-us

**Comment by Abdullah-AlEyoni** [comment]
for what I know the youtube script can't find the `9PoZXr8dxFA ` id video so send an error.
so what I did is download the video using https://www.y2mate.com/ and give it the URL for the video 
`https://www.youtube.com/watch?v= {video_id}`
 for your case will be
 `https://www.youtube.com/watch?v=9PoZXr8dxFA`
and edit the data.json file and change the video id `9PoZXr8dxFA` to author id for example `1YnNLi_Dy5M`.

I think u will find the id in data.json in the first part file

**Comment by udacimak** [comment]
This is a duplicate issue of #79 

I have fixed the issue. Please update Udacimak and try again
