### ISSUE TITLE
fail to retrieve "http://yaroslavvb.com/upload/notMNIST/nmn.png"

### ISSUE THREAD

**Issue by jacky-ttt** [udacimak/udacimak#8]
I encounter this error when udacimak tries to retrieve "http://yaroslavvb.com/upload/notMNIST/nmn.png". Maybe because it is not https?
```
2018-11-16T08:08:12.805Z [[31merror[39m]: ERROR [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: yaroslavvb.com. is not in the cert's altnames: DNS:*.accountservergroup.com, DNS:accountservergroup.com
CODE: ERR_TLS_CERT_ALTNAME_INVALID
STACK: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: yaroslavvb.com. is not in the cert's altnames: DNS:*.accountservergroup.com, DNS:accountservergroup.com
    at Object.checkServerIdentity (tls.js:228:17)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1059:27)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
```

**Comment by udacimak** [comment]
Thanks for reporting.
`http` or `https` doesn't matter.
If possible, could you email me the JSON file to udacimak@tutanota.com so I can have a better look?

**Comment by udacimak** [comment]
@jacky-ttt 
I've fixed the issue according to here:
- https://github.com/request/request/issues/1777#issuecomment-152323328

Enjoy!
