### ISSUE TITLE
stuck at getting video

### ISSUE THREAD

**Issue by JosephSafwat** [udacimak/udacimak#81]
? Getting Youtube video id pZ0J6PF6bqI information
2020-03-13T13:28:52.948Z [error]: ERROR: status code 500
STACK: Error: status code 500
    at Request.response (C:\Users\joseph\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\youtube-dl.js:67:35)
    at Request.emit (events.js:311:20)
    at Request.onRequestResponse (C:\Users\joseph\AppData\Roaming\npm\node_modules\udacimak\node_modules\request\request.js:1059:10)
    at ClientRequest.emit (events.js:311:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:476:22)
    at TLSSocket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)

**Comment by Ghaleb-alnakhlani** [comment]
I second this I have the same issue

**Comment by udacimak** [comment]
This is a duplicate issue of #79 

I have fixed the issue. Please update Udacimak and try again
