### ISSUE TITLE
failed on downloading youtube video

### ISSUE THREAD

**Issue by ahmedhany7** [udacimak/udacimak#92]
on running render command

- Delaying Youtube download for further 0.0 seconds
- Getting Youtube video id 9QadFJRKrEA information
× Getting Youtube video id 9QadFJRKrEA information
2020-03-27T19:53:27.260Z [error]: ERROR: Command failed with UNKNOWN: C:\Users\ahmed\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin\youtube-dl.exe --dump-json -f best -f=22/18/17 --encoding utf8 http://www.youtube.com/watch?v=9QadFJRKrEA
spawn UNKNOWN
CODE: UNKNOWN
STACK: Error: Command failed with UNKNOWN: C:\Users\ahmed\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin\youtube-dl.exe --dump-json -f best -f=22/18/17 --encoding utf8 http://www.youtube.com/watch?v=9QadFJRKrEA
spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:405:11)
    at Object.spawn (child_process.js:548:9)
    at execa (C:\Users\ahmed\AppData\Roaming\npm\node_modules\udacimak\node_modules\execa\index.js:80:26)
    at execa (C:\Users\ahmed\AppData\Roaming\npm\node_modules\udacimak\node_modules\universalify\index.js:23:13)
    at youtubeDl (C:\Users\ahmed\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\youtube-dl.js:23:10)
    at call (C:\Users\ahmed\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\youtube-dl.js:152:10)
    at Function.getInfo (C:\Users\ahmed\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\youtube-dl.js:237:3)
    at module.exports (C:\Users\ahmed\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\lib\youtube-dl.js:99:8)
    at C:\Users\ahmed\AppData\Roaming\npm\node_modules\udacimak\lib\commands\utils\downloadYoutube.js:89:42

**Comment by ahmedhany7** [comment]
solved by replacing youtube-dl.exe from here http://ytdl-org.github.io/youtube-dl/

**Comment by udacimak** [comment]
I have just released an update for Udacimak that may have fixed this. Can you try uninstalling Udacimak and install it again to see if this error has been solved?

**Comment by 1871vinayak** [comment]
Yeah there's an update `v1.6.0` with fix for this issue you can follow the steps to get it working for you.
- Uninstall
`npm uninstall -g udacimak`
- Install
`npm install -g udacimak`

**Comment by yumengdong** [comment]
The new version fixed this issue. However, when I tried to update the version, ```npm install -g udacimak``` or ```sudo npm install -g udacimak``` gave me permission error. Similar to [issue1](https://github.com/udacimak/udacimak/issues/1)
I had to use yarn: 
```
yarn global add udacimak
```

**Comment by udacimak** [comment]
> The new version fixed this issue. However, when I tried to update the version, `npm install -g udacimak` or `sudo npm install -g udacimak` gave me permission error. Similar to [issue1](https://github.com/udacimak/udacimak/issues/1)
> I had to use yarn:
> 
> ```
> yarn global add udacimak
> ```

Yes this issue has happened in the past but I'm not sure what's causing it, probably not Udacimak.

Good to hear that Youtube download is working for you now.
