### ISSUE TITLE
Unable to render course

### ISSUE THREAD

**Issue by trydalch** [udacimak/udacimak#93]
Attempting to run this using the WSL on Windows 10. 

```udacimak render React\ v5.0.0/
2020-03-27T20:37:37.533Z [info]: Image already exists. Skip downloading /mnt/c/Users/Trevor.Rydalch/Videos/Udacity/React v5.0.0/img/react-classroom.jpg
2020-03-27T20:37:37.568Z [info]: Completed rendering Nanodegree summary file /mnt/c/Users/Trevor.Rydalch/Videos/Udacity/React v5.0.0/index.html
2020-03-27T20:37:37.571Z [info]: ____________________

2020-03-27T20:37:37.608Z [info]: Completed rendering lesson summary file /mnt/c/Users/Trevor.Rydalch/Videos/Udacity/React v5.0.0/Part 01-Module 01-Lesson 01_Welcome to the React Nanodegree Program/index.html
2020-03-27T20:37:37.609Z [info]: ____________________

2020-03-27T20:37:37.639Z [info]: Completed rendering lesson file /mnt/c/Users/Trevor.Rydalch/Videos/Udacity/React v5.0.0/Part 01-Module 01-Lesson 01_Welcome to the React Nanodegree Program/01. Rating Your Career Confidence.html
2020-03-27T20:37:37.640Z [info]: ____________________

✖ Getting Youtube video id GONrgnKbuxg information
2020-03-27T20:37:37.677Z [error]: ERROR: Command failed with exit code 127: /root/.nvm/versions/node/v13.5.0/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -f=22/18/17 http://www.youtube.com/watch?v=GONrgnKbuxg
STACK: Error: Command failed with exit code 127: /root/.nvm/versions/node/v13.5.0/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -f=22/18/17 http://www.youtube.com/watch?v=GONrgnKbuxg
    at makeError (/root/.nvm/versions/node/v13.5.0/lib/node_modules/udacimak/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/root/.nvm/versions/node/v13.5.0/lib/node_modules/udacimak/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)```

**Comment by ahmedhany7** [comment]
download youtube-dl.exe from here http://ytdl-org.github.io/youtube-dl/
then replace it

**Comment by trydalch** [comment]
I ended up doing the download on my mac instead and the renders are running.

It times out quite often, but then I just restart it and it keeps going.

**Comment by josemejiasji** [comment]
Hi, I have the same issue in macos 10.15.4. I think is related to youtube-dl version.

**Comment by josemejiasji** [comment]
My issue was with OpenSSL. I manage to fix it following this: https://stackoverflow.com/questions/59269208/errorrootcode-for-hash-md5-was-not-found-when-using-any-hg-mercurial-command

**Comment by MdTalhaZubayer** [comment]
https://github.com/udacimak/udacimak/issues/100#issuecomment-606465183

**Comment by 1871vinayak** [comment]
There's an update `v1.6.0` with fix for this issue you can follow the steps to get it working for you.
- Uninstall
`npm uninstall -g udacimak`
- Install
`npm install -g udacimak`
