### ISSUE TITLE
STACK: Error: Path to downloaded Udacity course/Nanodegree doesn't exist.

### ISSUE THREAD

**Issue by kevinlaiGH** [udacimak/udacimak#98]
**The bug**
Path to downloaded Udacity course/Nanodegree doesn't exist.

**To Reproduce**
1.  `udacimak render /Users/kevinlai/Documents/Full-Stack Developer v1.0.0`
2. `2020-03-30T11:42:43.282Z [error]: ERROR: Path to downloaded Udacity course/Nanodegree doesn't exist.
STACK: Error: Path to downloaded Udacity course/Nanodegree doesn't exist.
    at renderCourse (/usr/local/lib/node_modules/udacimak/lib/commands/render/functions/renderCourse.js:43:11)
    at async render (/usr/local/lib/node_modules/udacimak/lib/commands/render/index.js:20:5)`

**Comment by kevinlaiGH** [comment]
Solve it by putting this in terminal:
`"udacimak render "/Users/kevinlai/Documents/Full-Stack Developer v1.0.0"`
